import { describe, expect, test } from 'vitest';
import { applyCommand, combatStats, createGame, maxEnergy, maxHealth, parseSession, reachable, restBudget } from '../src/engine/game';
import { ABILITIES, ENEMIES, HEROES, REGIONS } from '../src/data/content';
import type { Command, GameState } from '../src/engine/types';

function soloBattle(enemyId='scarlet',heroId='grom'){
 let s=createGame(17);const h=s.heroes.find(h=>h.id===heroId)!;h.location=s.enemies.find(e=>e.id===enemyId)!.region;
 s=applyCommand(s,{type:'challenge',heroId,enemyId});return s;
}
function customRoll(s:GameState,colors:('red'|'blue'|'green')[]){s.battle!.stage='rolled';s.battle!.dice=colors.map((color,i)=>({id:i,color,value:8,heroId:s.battle!.participants[0],rerolled:false}));return s;}

describe('World and turn rules',()=>{
 test('world graph is connected and symmetric',()=>{for(const r of REGIONS)for(const id of r.neighbors)expect(REGIONS.find(x=>x.id===id)?.neighbors).toContain(r.id);const seen=new Set<string>();const q=[REGIONS[0].id];while(q.length){const id=q.shift()!;if(seen.has(id))continue;seen.add(id);q.push(...REGIONS.find(r=>r.id===id)!.neighbors);}expect(seen.size).toBe(REGIONS.length);});
 test('each class has a free ability and all quest targets exist',()=>{for(const h of HEROES)expect(ABILITIES.some(a=>a.classId===h.classId&&a.price===0)).toBe(true);for(const q of createGame().quests)expect(ENEMIES.some(e=>e.id===q.enemyId&&e.faction===q.faction)).toBe(true);});
 test('Horde starts and every hero receives two actions',()=>{const s=createGame();expect(s.faction).toBe('horde');expect(s.heroes.every(h=>h.actions===2)).toBe(true);});
 test('a travel action traverses at most two steps',()=>{const s=createGame();const routes=reachable(s,s.heroes[0]);expect(routes.undercity).toHaveLength(1);expect(routes.sepulcher).toHaveLength(2);expect(routes.stratholme).toBeUndefined();const n=applyCommand(s,{type:'travel',heroId:'grom',destination:'sepulcher'});expect(n.heroes[0].actions).toBe(1);expect(s.heroes[0].location).toBe('brill');});
 test('independent enemies end travel and force the next action',()=>{const s=createGame();const routes=reachable(s,s.heroes[0]);expect(routes.bulwark).toBeDefined();expect(routes.andorhal).toBeUndefined();const n=applyCommand(s,{type:'travel',heroId:'grom',destination:'bulwark'});expect(reachable(n,n.heroes[0])).toEqual({});expect(()=>applyCommand(n,{type:'train',heroId:'grom',abilityIds:['shield-block']})).toThrow('Nezavisno');});
 test('friendly flight paths cost one movement step and enemy home is forbidden',()=>{const s=createGame();const routes=reachable(s,s.heroes[0]);expect(routes.tarren).toHaveLength(1);expect(routes.hillsbrad).toHaveLength(2);expect(routes.southshore).toBeUndefined();});
 test('opponent and exhausted heroes cannot act',()=>{const s=createGame();expect(()=>applyCommand(s,{type:'travel',heroId:'aldric',destination:'hillsbrad'})).toThrow('frakcija');s.heroes[0].actions=0;expect(()=>applyCommand(s,{type:'travel',heroId:'grom',destination:'monastery'})).toThrow('obje akcije');});
 test('turn changes reset only the incoming faction; world event updates actual state',()=>{let s=createGame();s=applyCommand(s,{type:'endTurn'});expect(s.faction).toBe('alliance');expect(s.heroes[0].actions).toBe(0);s=applyCommand(s,{type:'endTurn'});expect(s.heroes[0].actions).toBe(2);expect(s.heroes.every(h=>h.gold===6)).toBe(true);s=applyCommand(applyCommand(s,{type:'endTurn'}),{type:'endTurn'});expect(s.enemies.find(e=>e.id==='spider')!.count).toBe(2);});
 test('rest splits the fixed budget and never exceeds capacities',()=>{const s=createGame();const h=s.heroes[0];h.health=3;h.energy=1;expect(restBudget(h)).toBe(3);const n=applyCommand(s,{type:'rest',heroId:h.id,health:2});expect(n.heroes[0].health).toBe(5);expect(n.heroes[0].energy).toBe(2);expect(n.heroes[0].actions).toBe(1);expect(()=>applyCommand(s,{type:'rest',heroId:h.id,health:-2})).toThrow();});
 test('training enforces class, cost, level, uniqueness, and atomic failure',()=>{const s=createGame();const serialized=JSON.stringify(s);expect(()=>applyCommand(s,{type:'train',heroId:'grom',abilityIds:['shield-block','shield-block']})).toThrow();expect(()=>applyCommand(s,{type:'train',heroId:'grom',abilityIds:['frostbolt']})).toThrow();expect(()=>applyCommand(s,{type:'train',heroId:'grom',abilityIds:['mortal-strike']})).toThrow();expect(JSON.stringify(s)).toBe(serialized);const n=applyCommand(s,{type:'train',heroId:'grom',abilityIds:['shield-block']});expect(n.heroes[0].gold).toBe(2);expect(n.heroes[0].learned).toContain('shield-block');});
 test('shop validates location and equips only one item per slot',()=>{let s=createGame();s.heroes[0].gold=10;s=applyCommand(s,{type:'town',heroId:'grom',itemId:'steel-blade'});s=applyCommand(s,{type:'town',heroId:'grom',itemId:'oak-staff'});expect(s.heroes[0].equipment).toEqual(['oak-staff']);expect(s.heroes[0].gold).toBe(4);s.heroes[0].location='monastery';s.heroes[0].actions=1;expect(()=>applyCommand(s,{type:'town',heroId:'grom',itemId:'chainmail'})).toThrow('grad');});
});
describe('Combat sequencing and effect scripts',()=>{
 test('group members each pay one action and must be at the same location',()=>{let s=createGame();for(const h of s.heroes.slice(0,3))h.location='monastery';s=applyCommand(s,{type:'challenge',heroId:'grom',enemyId:'scarlet',allies:['lyra','karn']});expect(s.battle!.participants).toHaveLength(3);expect(s.heroes.slice(0,3).every(h=>h.actions===1)).toBe(true);expect(()=>applyCommand(s,{type:'endTurn'})).toThrow('borbu');});
 test('cannot challenge opponents faction quest or bypass independent enemies',()=>{const s=createGame();s.heroes[0].location='hillsbrad';expect(()=>applyCommand(s,{type:'challenge',heroId:'grom',enemyId:'gnoll'})).toThrow('druge frakcije');s.enemies.push({...s.enemies[0],id:'independent',kind:'independent',faction:undefined,region:'hillsbrad'});expect(()=>applyCommand(s,{type:'challenge',heroId:'grom',enemyId:'gnoll'})).toThrow();});
 test('blue hits remove enemies before they can attack',()=>{const s=customRoll(soloBattle(),['blue','blue','blue','blue']);const health=s.heroes[0].health;const n=applyCommand(s,{type:'resolve'});expect(n.battle!.outcome).toBe('victory');expect(n.heroes[0].health).toBeGreaterThanOrEqual(health);expect(n.completedQuests).toContain('q-scarlet');});
 test('red hits defend then damage while green hits only defend',()=>{const s=customRoll(soloBattle(),['red','green']);const n=applyCommand(s,{type:'resolve'});expect(n.heroes[0].health).toBe(6);expect(n.battle!.remaining).toBe(2);expect(n.battle!.damage).toBe(1);expect(n.battle!.outcome).toBeUndefined();});
 test('attrition cannot kill enemies until after their attack',()=>{const s=customRoll(soloBattle(),[]);s.battle!.attrition=4;s.heroes[0].health=1;const n=applyCommand(s,{type:'resolve'});expect(n.battle!.outcome).toBe('defeat');expect(n.enemies.find(e=>e.id==='scarlet')!.count).toBe(2);expect(n.heroes[0].location).toBe('brill');});
 test('damage persists across rounds, consumed dice and buffs do not',()=>{let s=customRoll(soloBattle(),['blue']);s=applyCommand(s,{type:'resolve'});expect(s.battle!.damage).toBe(1);s=applyCommand(s,{type:'nextRound'});expect(s.battle!.damage).toBe(1);expect(s.battle!.dice).toEqual([]);expect(s.battle!.round).toBe(2);});
 test('abilities charge energy once and duplicate or unlearned powers are rejected',()=>{let s=soloBattle();const before=JSON.stringify(s);expect(()=>applyCommand(s,{type:'roll',powers:{grom:['heroic-strike','heroic-strike']}})).toThrow();expect(()=>applyCommand(s,{type:'roll',powers:{grom:['shield-block']}})).toThrow();expect(JSON.stringify(s)).toBe(before);s=applyCommand(s,{type:'roll',powers:{grom:['heroic-strike']}});expect(s.heroes[0].energy).toBe(3);expect(s.battle!.dice.filter(d=>d.color==='red')).toHaveLength(5);expect(()=>applyCommand(s,{type:'roll',powers:{}})).toThrow('fazi');});
 test('seven dice limit is enforced separately per color',()=>{const s=createGame();const h=s.heroes[0];h.level=5;h.equipment=['runeblade'];expect(combatStats(h,['heroic-strike','mortal-strike']).pool.red).toBe(7);expect(combatStats(h,['heroic-strike']).pool.green).toBe(2);});
 test('each die can only be rerolled once and rerolls belong to a hero',()=>{let s=soloBattle();s.heroes[0].equipment=['ranger-charm'];s=applyCommand(s,{type:'roll',powers:{}});s=applyCommand(s,{type:'reroll',dieIds:[0]});expect(s.battle!.dice[0].rerolled).toBe(true);expect(()=>applyCommand(s,{type:'reroll',dieIds:[0]})).toThrow('već');expect(()=>applyCommand(s,{type:'reroll',dieIds:[1]})).toThrow('dovoljno');});
 test('independent kills do not grant quest XP or gold',()=>{const s=customRoll(soloBattle('spider'),['blue','blue']);const n=applyCommand(s,{type:'resolve'});expect(n.heroes[0].xp).toBe(0);expect(n.heroes[0].gold).toBe(5);expect(n.completedQuests).toEqual([]);});
 test('boss victory ends campaign and closeBattle remains legal',()=>{const s=customRoll(soloBattle('lich'),Array.from({length:18},()=> 'blue' as const));const n=applyCommand(s,{type:'resolve'});expect(n.status).toBe('victory');expect(n.winner).toBe('horde');expect(applyCommand(n,{type:'closeBattle'}).battle).toBeNull();expect(()=>applyCommand(n,{type:'endTurn'})).toThrow('završena');});
 test('timeout follows the documented prototype rule at 30 turns',()=>{let s=createGame();for(let i=0;i<30;i++)s=applyCommand(s,{type:'endTurn'});expect(s.turn).toBe(30);expect(s.status).toBe('expired');});
 test('retreat uses the documented prototype recovery policy',()=>{const s=soloBattle();const n=applyCommand(s,{type:'flee'});expect(n.battle!.outcome).toBe('fled');const h=n.heroes[0];expect(h.health).toBe(maxHealth(h));expect(h.energy).toBe(maxEnergy(h));expect(h.actions).toBe(0);expect(h.gold).toBe(4);});
});
describe('Replay saves and deterministic simulation',()=>{
 test('saved command history exactly reproduces dice and state',()=>{const commands:Command[]=[{type:'travel',heroId:'grom',destination:'monastery'},{type:'challenge',heroId:'grom',enemyId:'scarlet'},{type:'roll',powers:{grom:['heroic-strike']}},{type:'resolve'}];let s=createGame(991);for(const command of commands)s=applyCommand(s,command);const raw=JSON.stringify({format:'lordaeron-save',version:1,seed:991,roster:s.heroes.map(h=>h.id),commands});expect(parseSession(raw).state).toEqual(s);});
 test('malformed, manipulated and unknown saves fail closed',()=>{expect(()=>parseSession('{}')).toThrow();expect(()=>parseSession(JSON.stringify({format:'lordaeron-save',version:1,seed:0,roster:['grom','aldric'],commands:[]}))).toThrow();expect(()=>parseSession(JSON.stringify({format:'lordaeron-save',version:1,seed:7,roster:['grom','aldric'],commands:[{type:'arbitrary-code'}]}))).toThrow();});
 test('many seeds finish combat without illegal resources or non d8 rolls',()=>{for(let seed=1;seed<=50;seed++){let s=createGame(seed);s.heroes[0].location='monastery';s=applyCommand(s,{type:'challenge',heroId:'grom',enemyId:'scarlet'});let rounds=0;while(!s.battle!.outcome&&rounds++<60){s=applyCommand(s,{type:'roll',powers:{grom:s.heroes[0].energy>0?['heroic-strike']:[]}});expect(s.battle!.dice.every(d=>d.value>=1&&d.value<=8)).toBe(true);s=applyCommand(s,{type:'resolve'});if(!s.battle!.outcome)s=applyCommand(s,{type:'nextRound'});}expect(s.battle!.outcome).toBeDefined();expect(s.heroes.every(h=>h.energy>=0&&h.health>=0&&h.actions>=0)).toBe(true);}});
});
