import { useState } from 'react';
import { BASE_PACK as p, CLASS_CARDS, BASE_ITEMS } from '../data/base';
import { Icon } from '../components';
import { CharacterCard, GameCard } from './parts';
import { CreatureCard, EventCardView, OverlordCard, QuestCard } from './design-system';
const tabs=[['powers','Moći',108],['talents','Talenti',108],['items','Predmeti',120],['quests','Questovi',80],['events','Događaji',52],['heroes','Junaci',16],['creatures','Bestijarij',13],['bosses','Overlordi',3]] as const;
export default function BaseCatalog({inspect}:{inspect:(id:string)=>void}){
 const [tab,setTab]=useState<string>('powers'),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(0);
 const items=tab==='quests'?p.quests:tab==='events'?p.events:tab==='heroes'?p.characters:tab==='creatures'?p.creatures:tab==='bosses'?p.overlords:tab==='items'?BASE_ITEMS:CLASS_CARDS.filter(c=>c.kind===(tab==='talents'?'talent':'power'));
 const filtered=items.filter(c=>(`${c.name} ${'classId'in c?c.classId:''} ${'faction'in c?c.faction:''}`).toLowerCase().includes(query.toLowerCase())&&(!filter||('classId'in c&&c.classId===filter)||('faction'in c&&c.faction===filter)||('deck'in c&&c.deck===filter)));
 const filters=tab==='quests'||tab==='heroes'?['horde','alliance']:tab==='items'?['triangle','square','circle','special']:['powers','talents'].includes(tab)?['warrior','mage','hunter','priest','rogue','warlock','paladin','druid','shaman']:[];
 return <section className="base-catalog"><div className="catalog-intro"><div><span className="eyebrow">OSNOVNA IGRA · 2005 + FAQ</span><h2>Knjiga Lordaerona</h2><p>Originalne sposobnosti i vrijednosti u novom dizajnu.</p></div><label className="catalog-search"><Icon name="search"/><input value={query} placeholder="Pronađi kartu…" aria-label="Pretraži katalog" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div><nav className="catalog-tabs">{tabs.map(([id,label,count])=><button className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setFilter('');setPage(0);}}>{label}<b>{count}</b></button>)}</nav><div className="catalog-filter"><span>{filtered.length} rezultata</span>{filters.length>0&&<select value={filter} aria-label="Filtriraj katalog" onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="">Svi {tab==='items'?'špilovi':tab==='quests'||tab==='heroes'?'':'likovi'}</option>{filters.map(f=><option key={f}>{f}</option>)}</select>}<span className="catalog-pagination"><button className="icon-button" disabled={page===0} aria-label="Prethodna stranica" onClick={()=>setPage(n=>n-1)}>←</button>{page+1} / {Math.max(1,Math.ceil(filtered.length/24))}<button className="icon-button" aria-label="Sljedeća stranica" disabled={(page+1)*24>=filtered.length} onClick={()=>setPage(n=>n+1)}>→</button></span></div><div className="base-card-grid">{filtered.slice(page*24,page*24+24).map(c=>'abilities'in c?<GameCard key={c.id} card={c} onClick={()=>inspect(c.id)}/>: 'spawns'in c?<QuestCard key={c.id} quest={c}/>: 'fate'in c?<EventCardView key={c.id} event={c}/>: 'capacities'in c?<CharacterCard key={c.id} id={c.id}/>: 'combat'in c?<OverlordCard key={c.id} overlord={c}/>:<CreatureCard key={c.id} creature={c}/>)}</div></section>;
}
