import { useState } from 'react';
import { BASE_PACK as p } from '../data/base';
import { capacity, card, character } from '../rules/common';
import { bagSize, equipped, heroSlots, petCapacity } from '../rules/inventory';
import type { Card, Command, Hero, Slot } from '../rules/model';
import { Icon, ResourceBar } from '../components';
import { CardArt, AbilityArt, FactionCrest } from './Art';
import { HeroPortrait, GameCard } from './parts';
import { triggerLabels } from './design-system';
import { conditionText, effectText, staticCardText } from './rules-text';
import { regionName } from './event-text';
import ClassDeck, { energyLabel } from './ClassDeck';
import RulesText from './RulesText';

/** Keep every timing, conditional and strength visible, including printed powers. */
export function CardRules({value:c}:{value:Card}){
 const groups=c.abilities.filter((a,i,all)=>!a.usageGroup||all.findIndex(v=>v.usageGroup===a.usageGroup)===i);
 const rule=(a:Card['abilities'][number])=><p key={a.id}><strong>{triggerLabels[a.timing]??a.timing}{a.automatic?' · passive':''}{a.cost!==undefined?` · ${a.cost} energy`:''}</strong>{a.startOnly&&<em>At the start of this step. </em>}{a.condition&&<em>If <RulesText>{conditionText(a.condition)}</RulesText>: </em>}{a.requires&&<em>After using {triggerLabels[c.abilities.find(v=>v.id===a.requires)?.timing??'']??a.requires}. </em>}{a.freeIf&&<em>Free if <RulesText>{conditionText(a.freeIf)}</RulesText>. </em>}<RulesText>{a.effects.map(effectText).join(' · ')}</RulesText></p>;
 return <div className="inscribed-rules">{groups.map(a=>{const choices=a.usageGroup?c.abilities.filter(v=>v.usageGroup===a.usageGroup):[a];return <div className="inscribed-ability" key={a.id}>{rule(a)}{choices.length>1&&<details className="ability-strengths"><summary>{choices.length} strength options · choose one</summary>{choices.slice(1).map(rule)}</details>}</div>;})}{staticCardText(c).map(t=><p key={t}><RulesText>{t}</RulesText></p>)}</div>;
}
export const slotLabel=(s:Slot)=>s.stanceOnly?'Stance':s.types.map(t=>({instant:'Instant',active:'Active / constant',ranged:'Ranged',melee:'Melee',general:'General',armor:'Armor',bag:'Bag'}[t])).join(' / ');
export function startingHero(id:string):Hero {const d=character(p,id);return {id,location:d.faction==='horde'?'brill':'southshore',...d.capacities[0],gold:5,level:1,xp:0,actions:2,curse:0,stun:0,learned:[],talents:[],bag:[],slots:d.slots.map(()=>({addons:[]})),pets:{},auctionItems:[],talentChoices:[]};}
export default function CharacterSheet({hero:h,legal=[],inspect,open,preview=false}:{hero:Hero;legal?:Command[];inspect:(id:string)=>void;open?:(panel:'manage'|'train'|'trade')=>void;preview?:boolean}){
 const [tab,setTab]=useState<'sheet'|'spellbook'|'bag'|'talents'|'class'>('sheet');
 const d=character(p,h.id),cap=capacity(p,h),slots=heroSlots(p,h),equippedIds=equipped(p,h);
 const can=(type:Command['type'])=>legal.some(c=>c.type===type&&(!('hero'in c)||c.hero===h.id));
 const powers=p.cards.filter(c=>c.kind==='power'&&!c.printed&&c.classId===d.classId);
 const slotView=(s:Slot,i:number)=>{const id=h.slots[i]?.card??s.printed,c=id?card(p,id):undefined;return <section key={i} className={`character-slot ${c?'occupied':'vacant'}`} aria-label={`Slot ${i+1}: ${slotLabel(s)}`}>
  <header><b>{String(i+1).padStart(2,'0')}</b><span>{slotLabel(s)}<small>{s.traits.includes('all')?'All traits':s.traits.join(' · ')}</small></span></header>
  {c?<><button className="equipped-heading" onClick={()=>inspect(c.id)}><CardArt card={c} fit="contain"/><span><small>{c.printed?'PRINTED ON SHEET':`LEVEL ${c.level}`} · {c.type==='active'?'ACTIVE':c.type==='instant'?'INSTANT':c.type.toUpperCase()}</small><strong>{c.name}</strong><em>{energyLabel(c)}</em></span><Icon name="expand" size={12}/></button><CardRules value={c}/>{c.petHealth&&<div className="pet-health"><Icon name="heart" size={12}/>Pet health {h.pets[c.id]??c.petHealth} / {petCapacity(p,h,c.id)}</div>}</>:<div className="slot-placeholder"><AbilityArt icon={s.types.includes('active')?d.classId:s.types.includes('melee')?'melee':s.types.includes('armor')?'armor':'arcane'}/><strong>Open {s.stanceOnly?'stance':'slot'}</strong><span>{s.types.includes('active')?'Learn powers, then equip during management.':'Equip a compatible card during management.'}</span></div>}
  {!!h.slots[i]?.addons.length&&<div className="sheet-attachments">{h.slots[i].addons.map(id=><div key={id}><button onClick={()=>inspect(id)}><CardArt card={card(p,id)}/><b>{card(p,id).name}</b></button><CardRules value={card(p,id)}/></div>)}</div>}
 </section>;};
 return <article className={`full-character-sheet ${d.faction}`} aria-label={`${d.name} character sheet`}>
  <aside className="sheet-identity"><div className="sheet-portrait"><HeroPortrait id={h.id}/><FactionCrest faction={d.faction}/><span className="sheet-level">{h.level}<small>LEVEL</small></span></div><div className="sheet-nameplate"><span>{d.race} · {d.classId}</span><h2>{d.name}</h2><p><Icon name="pin" size={12}/>{regionName(h.location)}{preview?' · starting profile':''}</p></div><ResourceBar type="health" value={h.health} max={cap.health}/><ResourceBar type="energy" value={h.energy} max={cap.energy}/><div className="sheet-currency"><span><Icon name="coins"/>{h.gold}<small>GOLD</small></span><span><Icon name="spark"/>{h.xp}<small>XP</small></span><span><Icon name="walk"/>{h.actions}<small>ACTIONS</small></span></div>
   {d.racial&&<section className="racial-inscription"><span className="sheet-eyebrow">RACIAL ABILITY</span><button onClick={()=>inspect(d.racial!)}><CardArt card={card(p,d.racial)}/><h3>{card(p,d.racial).name}</h3></button><CardRules value={card(p,d.racial)}/></section>}
   <div className="sheet-conditions"><span>Curse <b>{h.curse}</b></span><span>Stun <b>{h.stun}</b></span></div>
   {!preview&&<div className="sheet-controls"><button className="gold-button" disabled={!can('manage')} onClick={()=>open?.('manage')}><Icon name="shield" size={15}/>Manage equipment</button><small>{can('manage')?'Your management phase is ready.':'Use both actions for every ally to enter equipment management.'}</small><button className="quiet-button" disabled={!can('train')} onClick={()=>open?.('train')}><Icon name="book" size={15}/>Train powers · 1 action</button></div>}
  </aside>
  <div className="sheet-content"><div className="sheet-levels" aria-label="Level capacities">{d.capacities.map((v,i)=><div className={h.level===i+1?'current':''} key={i}><b>{['I','II','III','IV','V'][i]}</b><span><i className="health"><Icon name="heart" size={11}/>{v.health}</i><i className="energy"><Icon name="bolt" size={11}/>{v.energy}</i></span><small>{p.xp[i]} XP</small></div>)}</div>
   <nav className="sheet-tabs" aria-label="Character sections">{([['sheet','Equipment',slots.length],['class','Class deck',24-h.learned.length-h.talents.length],['spellbook','Spellbook',h.learned.length],['bag','Bag',`${bagSize(p,h.bag)} / 3`],['talents','Talents',`${h.talents.length} / 4`]] as const).map(([id,label,n])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}<b>{n}</b></button>)}</nav>
   {tab==='sheet'&&<><div className="sheet-section-title"><h3>Powers & equipment</h3><span>Starting abilities remain active until covered.</span></div><div className="power-slot-row">{slots.slice(0,3).map(slotView)}</div><div className="equipment-slot-row">{slots.slice(3).map((s,i)=>slotView(s,i+3))}</div></>}
   {tab==='class'&&<ClassDeck hero={h} inspect={inspect} legal={legal} onLearn={preview?undefined:()=>open?.('train')}/>}
   {tab==='spellbook'&&<><div className="sheet-section-title"><h3>{d.classId} spellbook</h3><span>{h.learned.length} learned · {powers.length} class powers</span></div><p className="sheet-help">Train purchases powers with gold. Learned powers wait here until you equip them in a compatible slot. Active powers spend energy when equipped; instant powers spend it when used.</p><div className="spellbook-summary"><b>{h.learned.length} learned powers</b><button className="quiet-button" onClick={()=>setTab('class')}>Browse class deck</button></div>{!h.learned.length&&<p className="panel-empty">Your spellbook is empty. Buy powers from your class deck with a Train or Town action.</p>}<div className="sheet-card-grid">{powers.filter(c=>h.learned.includes(c.id)).map(c=><div key={c.id} className={`spell-entry ${h.learned.includes(c.id)?'learned':''}`}><span className="spell-state">{equippedIds.includes(c.id)?'EQUIPPED':h.learned.includes(c.id)?'LEARNED':c.level>h.level?`UNLOCKS AT LEVEL ${c.level}`:`NOT LEARNED · ${c.price} GOLD`}</span><GameCard card={c} onClick={()=>inspect(c.id)}/></div>)}</div></>}
   {tab==='bag'&&<><div className="sheet-section-title"><h3>Traveller’s satchel</h3><span>3 item slots · powers go in your spellbook</span></div><div className="sheet-card-grid">{Array.from({length:Math.max(3,h.bag.filter(id=>!card(p,id).bagExempt).length)},(_,i)=>{const id=h.bag.filter(id=>!card(p,id).bagExempt)[i];return id?<GameCard key={id} card={card(p,id)} onClick={()=>inspect(id)}/>:<div className="bag-empty" key={i}><AbilityArt icon="town"/><strong>Bag slot {i+1}</strong><span>Ready for your next reward</span></div>;})}</div>{[...h.bag.filter(id=>card(p,id).bagExempt),...h.auctionItems].length>0&&<><h3>Special items · outside bag capacity</h3><div className="sheet-card-grid">{[...h.bag.filter(id=>card(p,id).bagExempt),...h.auctionItems].map(id=><GameCard key={id} card={card(p,id)} onClick={()=>inspect(id)}/>)}</div></>}</>}
   {tab==='talents'&&<><div className="sheet-section-title"><h3>Path of mastery</h3><span>One permanent talent at each new level</span></div><div className="talent-slots">{[2,3,4,5].map((level,i)=>{const id=h.talents[i];return <section key={level}><header>LEVEL {['','I','II','III','IV','V'][level]}<span>{level<=h.level?'Unlocked':`${p.xp[level-1]} XP`}</span></header>{id?<><button className="equipped-heading" onClick={()=>inspect(id)}><CardArt card={card(p,id)}/><strong>{card(p,id).name}</strong></button><CardRules value={card(p,id)}/></>:<div className="slot-placeholder"><AbilityArt icon="train"/><strong>{level<=h.level?'Talent choice pending':'A new talent awaits'}</strong><span>Choose one eligible talent when reaching level {level}.</span></div>}</section>;})}</div><details className="talent-library"><summary>Browse all {d.classId} talents</summary><div className="sheet-card-grid">{p.cards.filter(c=>c.kind==='talent'&&c.classId===d.classId).map(c=><GameCard key={c.id} card={c} onClick={()=>inspect(c.id)}/>)}</div></details></>}
  </div>
 </article>;
}
