import { useEffect, useRef, useState } from 'react';
import { Icon } from '../components';
import { DEVELOPMENT_PACK as p } from '../data/development-pack';
import { character } from '../rules/common';
import type { Command } from '../rules/model';
import type { GameView } from '../rules/view';
export default function CampaignMap({state,selected,heroId,legal,onSelect,onMove,focused,onToggleFocus}:{focused:boolean;onToggleFocus:()=>void;state:GameView;selected:string;heroId:string;legal:Command[];onSelect:(id:string)=>void;onMove:(c:Command)=>void}){
 const[camera,setCamera]=useState({zoom:1,x:0,y:0}),[routes,setRoutes]=useState(false),[dragging,setDragging]=useState(false);
 const canvas=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;panX:number;panY:number}|null>(null),didDrag=useRef(false),viewScale=useRef(0);
 const zoom=camera.zoom,ratio=1400/960;
 const clamp=(next:typeof camera)=>{const el=canvas.current;if(!el)return next;const width=Math.min(el.clientWidth,el.clientHeight*ratio),height=width/ratio;const x=Math.max(0,(width*next.zoom-el.clientWidth)/2),y=Math.max(0,(height*next.zoom-el.clientHeight)/2);return{...next,x:Math.max(-x,Math.min(x,next.x)),y:Math.max(-y,Math.min(y,next.y))};};
 const changeZoom=(amount:number)=>setCamera(current=>{const zoom=Math.max(1,Math.min(3.5,current.zoom+amount)),factor=zoom/current.zoom;return clamp({zoom,x:current.x*factor,y:current.y*factor});});
 const reset=()=>setCamera({zoom:1,x:0,y:0});
 const focusRegion=(id:string)=>{const el=canvas.current,r=p.regions.find(r=>r.id===id);if(!el||!r)return;const scale=Math.min(el.clientWidth/1400,el.clientHeight/960),zoom=Math.min(3.5,Math.max(1.65,el.clientWidth/(el.clientHeight*ratio)));setCamera(clamp({zoom,x:(800-r.x*16)*scale*zoom,y:(550-r.y*11.08)*scale*zoom}));};
 useEffect(()=>{
  const el=canvas.current;if(!el)return;
  const wheel=(event:WheelEvent)=>{event.preventDefault();const rect=el.getBoundingClientRect(),x=event.clientX-rect.left-rect.width/2,y=event.clientY-rect.top-rect.height/2;setCamera(current=>{const zoom=Math.max(1,Math.min(3.5,current.zoom+(event.deltaY<0?.15:-.15))),factor=zoom/current.zoom;return clamp({zoom,x:x-(x-current.x)*factor,y:y-(y-current.y)*factor});});};
  el.addEventListener('wheel',wheel,{passive:false});
  const resize=new ResizeObserver(()=>{const scale=Math.min(el.clientWidth/1400,el.clientHeight/960),previous=viewScale.current;viewScale.current=scale;setCamera(current=>{if(!previous||!scale)return clamp(current);const zoom=Math.max(1,Math.min(3.5,current.zoom*previous/scale)),factor=scale*zoom/(previous*current.zoom);return clamp({zoom,x:current.x*factor,y:current.y*factor});});});resize.observe(el);
  return()=>{el.removeEventListener('wheel',wheel);resize.disconnect();};
 },[]);
 useEffect(()=>{const location=state.heroes.find(h=>h.id===heroId)?.location;if(location)focusRegion(location);},[heroId]);
 const moves=legal.filter((c):c is Extract<Command,{type:'travel'}>=>c.type==='travel'&&c.hero===heroId);
 const possible=new Set(moves.map(c=>c.path.at(-1)));const destination=p.regions.find(r=>r.id===selected)!;
 const move=moves.find(c=>c.path.at(-1)===selected);const me=state.heroes.find(h=>h.id===heroId)!;
 return <section className="campaign-map"><div className="map-toolbar"><span><Icon name="compass"/> LORDAERON <small>{p.regions.length} regija</small><span className="map-hint">TOČKIĆ · ZOOM / POVUCI · POMAK</span></span><div><select className="map-jump" aria-label="Pronađi regiju" value={selected} onChange={e=>{onSelect(e.target.value);focusRegion(e.target.value);}}>{p.regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="icon-button" title="Pronađi svog junaka" aria-label="Pronađi svog junaka" onClick={()=>{onSelect(me.location);focusRegion(me.location);}}><Icon name="target"/></button><button className={`icon-button ${routes?'selected':''}`} title="Prikaži veze" aria-label="Prikaži veze" onClick={()=>setRoutes(v=>!v)}><Icon name="walk"/></button><button className="icon-button" aria-label="Smanji mapu" onClick={()=>changeZoom(-.25)}><Icon name="minus"/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Povećaj mapu" onClick={()=>changeZoom(.25)}><Icon name="plus"/></button><button className="icon-button" title="Cijela mapa (0)" aria-label="Cijela mapa" onClick={reset}><Icon name="reset"/></button><button className={`icon-button ${focused?'selected':''}`} title="Proširi mapu (F)" aria-label={focused?'Vrati karte uz mapu':'Proširi mapu'} onClick={onToggleFocus}><Icon name="expand"/></button></div></div>
 <div ref={canvas} className={`campaign-map-scroll ${dragging?'dragging':''}`} tabIndex={0} role="region" aria-label="Navigacija mapom: plus, minus, strelice, 0 za cijelu mapu" onKeyDown={e=>{if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='0')reset();else if(e.key==='+'||e.key==='=')changeZoom(.25);else if(e.key==='-')changeZoom(-.25);else setCamera(c=>clamp({...c,x:c.x+(e.key==='ArrowLeft'?55:e.key==='ArrowRight'?-55:0),y:c.y+(e.key==='ArrowUp'?55:e.key==='ArrowDown'?-55:0)}));}}} onPointerDown={e=>{if(e.button!==0)return;didDrag.current=false;drag.current={x:e.clientX,y:e.clientY,panX:camera.x,panY:camera.y};}} onPointerMove={e=>{const start=drag.current;if(!start)return;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>5){didDrag.current=true;setDragging(true);e.currentTarget.setPointerCapture(e.pointerId);setCamera(current=>clamp({...current,x:start.panX+e.clientX-start.x,y:start.panY+e.clientY-start.y}));}}} onPointerUp={e=>{drag.current=null;setDragging(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;setDragging(false);}} onClickCapture={e=>{if(didDrag.current){e.preventDefault();e.stopPropagation();}}}><svg viewBox="100 70 1400 960" style={{transform:`translate(${camera.x}px,${camera.y}px) scale(${zoom})`}} role="group" aria-label="Interaktivna mapa Lordaerona">
 <defs><radialGradient id="node-glow"><stop stopColor="#f5d17a" stopOpacity=".8"/><stop offset="1" stopColor="#f5d17a" stopOpacity="0"/></radialGradient><filter id="map-shadow"><feDropShadow dx="0" dy="2" stdDeviation="3" floodOpacity=".8"/></filter></defs>
  <image className="atlas-map-art" href="/assets/warcraft/lordaeron.webp" width="1600" height="1108"/>
  <rect x="100" y="70" width="1400" height="960" fill="#241708" opacity=".03" pointerEvents="none"/>
  {p.regions.flatMap(r=>r.neighbors.filter(id=>id>r.id).map(id=>{const n=p.regions.find(r=>r.id===id)!;return <line key={`${r.id}-${id}`} x1={r.x*16} y1={r.y*11.08} x2={n.x*16} y2={n.y*11.08} stroke="#f4da9b" strokeOpacity={routes?.42:.13} strokeWidth="2" strokeDasharray="5 4"/>;}))}
  {[['TIRISFAL',440,175],['SILVERPINE',265,503],['ALTERAC',624,598],['HILLSBRAD',579,1080],['WESTERN PLAGUELANDS',817,240],['EASTERN PLAGUELANDS',1220,107],['THE HINTERLANDS',1146,949]].map(([name,x,y])=><text className="atlas-zone-name" key={name} x={x} y={y} fontSize={String(name).length>15?13:18} textAnchor="middle">{name}</text>)}
  {move&&[me.location,...move.path].slice(1).map((id,i)=>{const from=p.regions.find(r=>r.id===[me.location,...move.path][i])!,to=p.regions.find(r=>r.id===id)!;return <line className="route-pulse" key={i} x1={from.x*16} y1={from.y*11.08} x2={to.x*16} y2={to.y*11.08} stroke="#ffe1a0" strokeWidth="4" strokeDasharray="9 6"/>;})}
  {p.regions.map(r=>{const x=r.x*16,y=r.y*11.08,active=r.id===selected,can=possible.has(r.id),enemies=state.enemies.filter(e=>e.region===r.id),people=state.heroes.filter(h=>h.location===r.id);return <g key={r.id} className={`map-region ${active?'selected':''}`} role="button" tabIndex={0} aria-label={`${r.name}${can?' — dostupno za putovanje':''}${enemies.length?` — ${enemies.length} čudovišta`:''}`} onClick={()=>onSelect(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(r.id);}}}>
   <title>{r.name} · {r.zone}{r.flight?' · let':''}{r.town?' · grad':''}{r.graveyard?' · groblje':''}</title>
   <circle cx={x} cy={y} r="20" fill="transparent"/>
   {(active||can)&&<circle cx={x} cy={y} r={active?33:22} fill="url(#node-glow)"/>}
   <circle cx={x} cy={y} r={active?11:7} fill={active?'#f5d28b':can?'#ddb56b':'#273431'} stroke={active?'#fff1c9':'#c8aa70'} strokeWidth="2"/>
   {enemies.length>0&&<g transform={`translate(${x+15},${y-18})`}><circle r="13" fill={enemies.some(e=>e.color==='blue')?'#255d97':enemies[0].faction==='horde'?'#802e32':'#284f73'} stroke="#dcc99a" strokeWidth="1.5"/><text textAnchor="middle" y="5" fontSize="14" fontWeight="700" fill="white">{enemies.length}</text></g>}
   {people.map((h,i)=><g key={h.id} transform={`translate(${x+(i-(people.length-1)/2)*23},${y-39})`} filter="url(#map-shadow)"><circle r="14" fill={character(p,h.id).faction==='horde'?'#862e35':'#285d8c'} stroke={h.id===heroId?'#ffe4a2':'#bdac8d'} strokeWidth={h.id===heroId?3:1.5}/><text textAnchor="middle" y="5" fontSize="12" fontWeight="700" fill="#fff2dc">{character(p,h.id).name.slice(0,2).toUpperCase()}</text></g>)}
   {!active&&(zoom>1.2||r.town||r.flight||enemies.length>0)&&<text className="atlas-region-name" x={x} y={y+24} textAnchor="middle" fontSize={r.town?15:12}>{r.name}</text>}
   {active&&<g filter="url(#map-shadow)"><rect x={x-110} y={y+17} width="220" height="29" rx="4" fill="#101a18" stroke="#baa170"/><text x={x} y={y+37} textAnchor="middle" fontSize="17" fill="#f4e1af">{r.name}</text></g>}
  </g>;})}
  {(()=>{const r=p.regions.find(r=>r.id===state.overlord.region);return r?<g transform={`translate(${r.x*16},${r.y*11.08})`}><path d="M-18 -32 L-12 -49 L0 -38 L12 -49 L18 -32 Z" fill="#ecd08e" stroke="#22150f" strokeWidth="3"/><text y="-56" textAnchor="middle" fontSize="18" fill="#ffdea0">OVERLORD</text></g>:null;})()}
 </svg></div>
 <div className="campaign-destination"><div><span className="eyebrow">{destination.zone}</span><h3>{destination.name}</h3><p>{destination.home?'Početna regija · ':''}{destination.town?'Grad · ':''}{destination.flight?'Letna tačka · ':''}{destination.graveyard?'Groblje · ':''}{state.enemies.filter(e=>e.region===selected).length} čudovišta u regiji</p></div><button className="gold-button" disabled={!move} onClick={()=>move&&onMove(move)}>Putuj ovdje <small>{move?`${move.path.length} / 2 koraka`:'Nedostupno'}</small><Icon name="walk"/></button></div>
 </section>;
}
