import { AbilityCard, CardFrame, triggerLabels } from './design-system';
import { effectText, conditionText, staticCardText } from './rules-text';
import { Icon } from '../components';
import { BASE_PACK as p } from '../data/base';
import { card, character } from '../rules/common';
import type { Card } from '../rules/model';
export const pretty=(s:string)=>s.replace(/ · probn[oi]( quest)?/g,'');
export const factionLabel=(f:string)=>f==='horde'?'Horda':f==='alliance'?'Alijansa':'Neriješeno';
export const phaseLabel:Record<string,string>={actions:'Akcije družine',management:'Upravljanje opremom','final-management':'Priprema završnog PvP-a',combat:'Borba',reward:'Nagrade i novi quest',event:'Događaj',finished:'Kraj kampanje',attacker:'Redoslijed napada',pool:'Pripremi kockice',penalty:'Stun / Curse','after-pool':'Nakon bacanja',reroll:'Ponovna bacanja','after-reroll':'Efekt čudovišta','after-tokens':'Nakon pogodaka',tokens:'Postavi pogotke',defense:'Odbrana',wounds:'Raspodijeli rane',resolution:'Razrješenje','round-end':'Kraj runde',over:'Ishod borbe'};
export function HeroPortrait({id,small=false}:{id:string;small?:boolean}){const c=character(p,id);return <span className={`portrait campaign-portrait ${small?'small':''}`} role="img" aria-label={c.name} style={{backgroundImage:'url(/assets/warcraft/characters-base.webp)',backgroundSize:'400% 400%',backgroundPosition:`${c.portrait%4*100/3}% ${Math.floor(c.portrait/4)*100/3}%`}}/>;}
export function CharacterCard({id}:{id:string}) {const c=character(p,id);return <CardFrame kind="JUNAK" title={c.name} subtitle={`${c.race} · ${c.classId} · ${factionLabel(c.faction)}`} accent={c.faction} art={<HeroPortrait id={id}/>} footer={<span>Kapaciteti lika · nivo 1–5</span>}><span className="character-cap-grid">{c.capacities.map((v,i)=><span key={i}><b>{i+1}</b><span><Icon name="heart" size={12}/>{v.health}</span><span><Icon name="bolt" size={12}/>{v.energy}</span></span>)}</span>{c.racial&&<span className="folio-effect"><b>{card(p,c.racial).name}</b>{cardText(card(p,c.racial))}</span>}<span className="folio-effect"><b>POČETNA OPREMA</b>{c.slots.flatMap(s=>s.printed?[card(p,s.printed).name]:[]).join(' · ')}</span></CardFrame>;}
export {effectText} from './rules-text';
export const cardText=(c:Card)=>[...c.abilities.map(a=>a.effects.map(effectText).join(' · ')),...staticCardText(c)].join(' / ');
export function GameCard({card,disabled=false,onClick,selected=false,footer}:{card:Card;disabled?:boolean;onClick?:()=>void;selected?:boolean;footer?:string}){
 return <AbilityCard card={card} disabled={disabled} onClick={onClick} selected={selected} footer={footer}>{card.abilities.filter((a,i,all)=>!a.usageGroup||all.findIndex(v=>v.usageGroup===a.usageGroup)===i).map(a=><span className="folio-effect" key={a.id}><b>{triggerLabels[a.timing]??a.timing}</b>{a.condition&&<em>{conditionText(a.condition)}. </em>}{a.cost!==undefined&&<em>{a.cost} energije. </em>}{a.freeIf&&<em>Bez troška ako {conditionText(a.freeIf)}. </em>}{a.effects.map(effectText).join(' · ')}{a.usageGroup&&<small>Izbor jačine: {card.abilities.filter(v=>v.usageGroup===a.usageGroup).length} opcija</small>}</span>)}{staticCardText(card).map(text=><span className="folio-effect" key={text}>{text}</span>)}</AbilityCard>;
}
