import { AbilityCard, CardFrame, triggerLabels } from './design-system';
import { Icon } from '../components';
import { DEVELOPMENT_PACK as p } from '../data/development-pack';
import { character } from '../rules/common';
import type { Card, Effect } from '../rules/model';
export const pretty=(s:string)=>s.replace(/ · probn[oi]( quest)?/g,'');
export const factionLabel=(f:string)=>f==='horde'?'Horda':f==='alliance'?'Alijansa':'Neriješeno';
export const phaseLabel:Record<string,string>={actions:'Akcije družine',management:'Upravljanje opremom','final-management':'Priprema završnog PvP-a',combat:'Borba',reward:'Nagrade i novi quest',event:'Događaj',finished:'Kraj kampanje',attacker:'Redoslijed napada',pool:'Pripremi kockice',penalty:'Stun / Curse','after-pool':'Nakon bacanja',reroll:'Ponovna bacanja','after-reroll':'Efekt čudovišta',tokens:'Postavi pogotke',defense:'Odbrana',wounds:'Raspodijeli rane',resolution:'Razrješenje','round-end':'Kraj runde',over:'Ishod borbe'};
export function HeroPortrait({id,small=false}:{id:string;small?:boolean}){const c=character(p,id);return <span className={`portrait campaign-portrait ${small?'small':''}`} role="img" aria-label={c.name} style={{backgroundPosition:`${c.portrait%3*50}% ${Math.floor(c.portrait/3)*50}%`}}/>;}
export function CharacterCard({id}:{id:string}) {const c=character(p,id);return <CardFrame kind="JUNAK" title={c.name} subtitle={`${c.classId} · ${factionLabel(c.faction)}`} accent={c.faction} art={<HeroPortrait id={id}/>} footer={<span>Kapaciteti lika · nivo 1–5</span>}><span className="character-cap-grid">{c.capacities.map((v,i)=><span key={i}><b>{i+1}</b><span><Icon name="heart" size={12}/>{v.health}</span><span><Icon name="bolt" size={12}/>{v.energy}</span></span>)}</span><span className="folio-effect"><b>POČETNE KARTE I RASNA MOĆ</b>Tekst čeka uvoz. Razvojna kampanja koristi probne sposobnosti.</span></CardFrame>;}
export function effectText(e:Effect):string{
 switch(e.op){case'dice':return`+${e.amount} ${e.color==='red'?'crvene':e.color==='blue'?'plave':'zelene'} kockice`;case'stat':return`${e.amount>=0?'+':''}${e.amount} ${e.stat==='reroll'?'ponovnih bacanja':e.stat==='attrition'?'iscrpljivanja':e.stat==='armor'?'oklopa':'prijetnje'}`;case'resource':return`${e.amount>=0?'+':''}${e.amount} ${e.resource==='health'?'zdravlja':e.resource==='energy'?'energije':'zlata'}${e.target==='friendly'?' savezniku':''}`;case'spot':return`Spot ${e.count} kockice → ${e.effects.map(effectText).join(', ')}`;case'remove':return`Ukloni ${e.count} kockice → ${e.effects.map(effectText).join(', ')}`;case'change':return`Promijeni rezultat u ${e.value}`;case'discard-self':return'Odbaci nakon upotrebe';case'condition':return`${e.amount} ${e.condition}`;case'heal-pet':return`Ljubimac: +${e.amount} zdravlja`;case'if':return'Uslovni efekt';case'token':return`+${e.amount} ${e.box}`;}
}
export const cardText=(c:Card)=>c.abilities.map(a=>a.effects.map(effectText).join(' · ')).join(' / ');
export function GameCard({card,disabled=false,onClick,selected=false,footer}:{card:Card;disabled?:boolean;onClick?:()=>void;selected?:boolean;footer?:string}){
 return <AbilityCard card={card} disabled={disabled} onClick={onClick} selected={selected} footer={footer}>{card.abilities.map(a=><span className="folio-effect" key={a.id}><b>{triggerLabels[a.timing]??a.timing}</b>{a.effects.map(effectText).join(' · ')}</span>)}</AbilityCard>;
}
