import { useState } from 'react';
import { CONTENT_COVERAGE, BASE_PACK as p } from '../data/base';
import { Icon } from '../components';

export default function RulesGuide({onSetup,onDesign}:{onSetup:()=>void;onDesign:()=>void}) {
 const [section,setSection]=useState<'guide'|'content'>('guide');
 return <section className="coverage-page rules-flow"><div className="rules-heading"><div><span className="eyebrow">BASE GAME 2005 + FAQ 1.4</span><h2>Rules for your table</h2></div><nav className="flow-tabs" aria-label="Rules sections"><button aria-pressed={section==='guide'} onClick={()=>setSection('guide')}>Quick guide</button><button aria-pressed={section==='content'} onClick={()=>setSection('content')}>Content & sources</button></nav></div>
 {section==='guide'?<div className="rules-grid"><article><Icon name="users"/><h3>Setup before your first turn</h3><p>Choose four or six unique classes and balanced factions. Setup previews starting resources, quests, merchant stock and the Overlord.</p><button className="quiet-button" onClick={onSetup}>Open setup guide <Icon name="arrow" size={14}/></button></article><article><Icon name="compass"/><h3>Two actions per character</h3><p>Characters of the active faction act in any order: Travel, Rest, Train, Town and Challenge. Then confirm equipment during management.</p><small>Keys 1–5 select actions · F opens the map · Esc returns</small></article><article><Icon name="swords"/><h3>Combat, step by step</h3><p>Choose the attacker, prepare and roll dice, use rerolls and abilities, place hits, assign wounds and resolve combat. Powers appear when available.</p></article><article><Icon name="trophy"/><h3>Victory</h3><p>Defeat the Overlord to win for your faction. The track repeats after turn 30 until the Overlord is defeated. Deadly PvP optionally changes combat damage.</p></article><article><Icon name="shield"/><h3>AI and local play</h3><p>Bots follow the same rules and legal actions. They cannot see deck order, future rolls or the opposing faction’s hidden Kazzak clues.</p><small>Open panels pause automatic turns. Your game saves as you play.</small></article><article><Icon name="map"/><h3>Travel through Lordaeron</h3><p>Move up to two regions across colored shared borders. Black edges are impassable. A friendly flight costs one step; entering a region with a blue creature ends movement.</p></article></div>:<div className="rules-reference"><table><thead><tr><th>Content</th><th>Count</th><th>Verified from scans</th></tr></thead><tbody>{CONTENT_COVERAGE.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.expected}</td><td>{c.note}</td></tr>)}</tbody></table><aside><Icon name="book" size={28}/><h3>From the original table</h3><p>{p.regions.length} bordered regions across seven zones. Quest tokens track remaining objectives, with faction colors.</p><p>Grey quests start the campaign. Replacements come from the green, yellow or red deck after resolving a quest.</p><div className="sources-list"><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/wowrules.pdf" target="_blank" rel="noreferrer">Official rulebook <Icon name="arrow" size={14}/></a><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/WoW_FAQ__v1_4.pdf" target="_blank" rel="noreferrer">FAQ / errata <Icon name="arrow" size={14}/></a><button className="quiet-button" onClick={onDesign}>Design system</button></div></aside></div>}
 </section>;
}
