import { useEffect, useState } from 'react';
import { BASE_PACK as p } from '../data/base';
import { capacity, card, character } from '../rules/common';
import { commandLabel } from '../rules/legal';
import type { Command, Hero } from '../rules/model';
import type { GameView } from '../rules/view';
import { Icon, Modal } from '../components';
import Map from './Map';
import QuestLedger, { QuestDetails } from './QuestLedger';
import { questMarkers } from './map-state';
import { GameIcon } from './GameIcon';
import { GameCard, HeroPortrait, factionLabel } from './parts';
import { BossPortrait, EventCardView, OverlordCard } from './design-system';
import { deckSymbol, regionName } from './event-text';
import CharacterSheet from './CharacterSheet';
import ClassDeck from './ClassDeck';
import { AnimatedValue, encounterProfile, ThreatLevel } from './feedback';
export type TablePanel='rest'|'train'|'town'|'challenge'|'manage'|'trade';
type Workspace='classes'|'characters'|'quests'|'merchant'|'encounters'|'party';
const workspaceLabels:Record<Workspace,string>={classes:'Class decks',characters:'Characters',quests:'Quests',merchant:'Merchant',encounters:'Encounter deck',party:'Party controls'};
export default function Tabletop({state,h,legal,controlled,bots,auto,botReady,botReason,selectHero,selected,selectRegion,inspect,open,send,botStep,toggleBots,focused,toggleFocus,notify,combatOpen=false,toggleCombat}:{state:GameView;h:Hero;legal:Command[];controlled:string[];bots:string[];auto:boolean;botReady:boolean;botReason:string;selectHero:(id:string)=>void;selected:string;selectRegion:(id:string)=>void;inspect:(id:string)=>void;open:(p:TablePanel)=>void;send:(c:Command)=>void;botStep:()=>void;toggleBots:()=>void;focused:boolean;toggleFocus:()=>void;notify:(s:string)=>void;combatOpen?:boolean;toggleCombat?:()=>void}){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[questSelection,setQuestSelection]=useState<string>(),[questInfo,setQuestInfo]=useState<string>();
 const pendingTalent=state.heroes.some(hero=>hero.talentChoices.length>0);
 useEffect(()=>{if(['combat','event','reward','finished'].includes(state.phase)||state.respawns.length||pendingTalent){setWorkspace(null);setQuestInfo(undefined);}},[state.phase,state.respawns.length,pendingTalent]);
 const selectedQuest=state.quests.includes(questSelection??'')?questSelection:undefined;
 const chooseQuest=(id:string,region?:string)=>{setQuestSelection(id);const target=region??questMarkers(p,state).find(m=>m.quest.id===id)?.region;if(target)selectRegion(target);setWorkspace(null);};
 const d=character(p,h.id),cap=capacity(p,h),boss=p.overlords.find(o=>o.id===state.overlord.id)!;
 const can=(type:Command['type'])=>legal.some(c=>c.type===type&&(!('hero'in c)||c.hero===h.id));
 const openAction=(panel:TablePanel)=>{setWorkspace(null);open(panel);};
 const management=state.phase==='management'||state.phase==='final-management';
 const pendingEquipment=state.heroes.filter(hero=>(state.phase==='final-management'||character(p,hero.id).faction===state.faction)&&!(state.phase==='final-management'?state.finalReady:state.managed).includes(hero.id));
 const nextHuman=pendingEquipment.find(hero=>legal.some(c=>c.type==='manage'&&c.hero===hero.id));
 const phaseCommand=legal.find(c=>c.type==='endActions'||c.type==='endManagement');
 const remainingActions=state.heroes.filter(hero=>character(p,hero.id).faction===state.faction).reduce((sum,hero)=>sum+hero.actions,0);
 const bossProfile=encounterProfile(state,boss.id)!;
 const extras=legal.filter(c=>'hero'in c&&c.hero===h.id&&['power-action','portal','summon','purify','peek','ability'].includes(c.type));
 const world=(state.world??[]).map(w=>p.events.find(e=>e.id===w.id)!);
 const nextEvent=Object.entries(p.track).find(([turn,kind])=>Number(turn)>state.turn&&kind==='event')?.[0];
 const tabs=(inside=false)=><nav className={`workspace-toggles ${inside?'inside':''}`} aria-label={inside?'Switch game panel':'Game panels'}>{([['characters','characters',state.heroes.length],['classes','train',state.heroes.length],['quests','quests',state.quests.length],['merchant','bag',state.merchant.length],['encounters','encounters',state.deckCounts.events],['party','armor',bots.length]] as const).map(([id,icon,n])=><button key={id} aria-pressed={workspace===id} aria-expanded={workspace===id} onClick={()=>setWorkspace(workspace===id?null:id)}><GameIcon name={icon} size={28}/><span>{workspaceLabels[id]}</span><b>{n}</b></button>)}<button className={`combat-nav-toggle ${state.phase==='combat'?'live':''}`} aria-pressed={combatOpen} aria-expanded={combatOpen} disabled={!toggleCombat} onClick={()=>{setWorkspace(null);toggleCombat?.();}}><GameIcon name="melee" size={28}/><span>Combat</span><b>{state.phase==='combat'?`R${state.battle?.round}`:'D8'}</b></button></nav>;
 return <div className="command-table">
  {questInfo&&<QuestDetails quest={p.quests.find(q=>q.id===questInfo)!} state={state} onClose={()=>setQuestInfo(undefined)} onLocate={id=>{selectRegion(id);setQuestInfo(undefined);setWorkspace(null);if(!focused)toggleFocus();}}/>}
  <div className="table-navigation">{tabs()}<span className="turn-preview">{state.phase==='finished'?'Campaign complete':nextEvent?`Next event · turn ${nextEvent}`:state.variants?.overlordOnly?'Next lap after turn 30':'Final PvP after turn 30'}</span></div>
  <div className="map-context"><button className="active-character-summary" onClick={()=>setWorkspace('characters')}>
   <span className="summary-portrait"><HeroPortrait id={h.id} small/><GameIcon name={d.classId} size={23}/></span>
   <span className="summary-name"><small>{d.classId} · LEVEL {h.level}</small><strong>{d.name}</strong></span>
   <span className="compact-vitals" key={h.id}>
    <span className="compact-stat health"><GameIcon name="health" size={27}/><span><small>Health</small><b><AnimatedValue value={h.health}/><em> / {cap.health}</em></b></span></span>
    <span className="compact-stat energy"><GameIcon name="energy" size={27}/><span><small>Energy</small><b><AnimatedValue value={h.energy}/><em> / {cap.energy}</em></b></span></span>
    <span className="compact-stat gold"><GameIcon name="gold" size={27}/><span><small>Gold</small><b><AnimatedValue value={h.gold}/></b></span></span>
   </span>
   <span className="summary-actions"><span className="action-pips" aria-label={`${h.actions} ${h.actions===1?'action':'actions'} remaining`}><i className={h.actions>0?'full':''}/><i className={h.actions>1?'full':''}/></span><small>Actions</small></span><Icon name="down" size={15}/>
  </button><button className="overlord-summary-button" onClick={()=>setWorkspace('encounters')}><BossPortrait id={boss.id}/><span><small>OVERLORD</small><strong>{boss.name}</strong></span><ThreatLevel value={bossProfile.threat} compact/><Icon name="right" size={15}/></button></div>
  {(management||state.phase==='actions'&&!h.actions)&&<section className="turn-guidance" aria-label="Next campaign step"><Icon name={management?'shield':'check'} size={22}/><div><strong>{management?'Prepare your party’s equipment':`${d.name.split(' ')[0]} has finished both actions`}</strong><p>{management?`${pendingEquipment.length} character${pendingEquipment.length===1?'':'s'} awaiting confirmation. Active powers spend energy when equipped.`:remainingActions?`${remainingActions} allied action${remainingActions===1?'':'s'} remaining before equipment management.`:'Your party is ready for equipment management.'}</p></div>{management&&nextHuman?<button className="gold-button" onClick={()=>{selectHero(nextHuman.id);openAction('manage');}}>Equip {character(p,nextHuman.id).name.split(' ')[0]}<Icon name="arrow" size={15}/></button>:phaseCommand?<button className="gold-button" onClick={()=>send(phaseCommand)}>{management?'End turn':'Manage equipment'}<Icon name="arrow" size={15}/></button>:<button className="quiet-button" onClick={()=>setWorkspace('party')}>Party controls<Icon name="users" size={15}/></button>}</section>}
  <Map onHero={selectHero} state={state} heroId={h.id} selected={selected} legal={legal} focused={focused} onToggleFocus={toggleFocus} onSelect={selectRegion} onMove={send} selectedQuest={selectedQuest} onQuest={chooseQuest} onInspectQuest={setQuestInfo}/>
  <div className="table-action-footer"><div className="current-location"><Icon name="pin" size={17}/><span>{regionName(h.location)}<small>{controlled.includes(h.id)?`${h.actions} of 2 actions remaining`:'Inspecting an AI character'}</small></span></div><div className="action-dock">{([['travel','Travel','travel'],['rest','Rest','rest'],['train','Train','train'],['town','Town','town'],['challenge','Challenge','melee']] as const).map(([type,label,icon],i)=><button key={type} disabled={!can(type)} title={can(type)?'Costs 1 action':type==='town'?'Visit a friendly town with an action remaining.':'Unavailable for this character in the current phase.'} onClick={()=>type==='travel'?(!focused?toggleFocus():notify('Select a highlighted region, review the route and confirm Travel.')):openAction(type)}><GameIcon name={icon} size={34}/><span>{label}</span><kbd>{i+1}</kbd></button>)}</div><button className={`quiet-button bot-status ${auto?'running':''}`} onClick={toggleBots}><Icon name={auto?'minus':'arrow'} size={13}/>{auto?'Pause AI':'Run AI'}</button></div>
  {workspace&&<Modal title={workspaceLabels[workspace]} wide className="workspace-modal" onClose={()=>setWorkspace(null)}>{tabs(true)}<div className={`workspace-body workspace-${workspace}`}>
   {(workspace==='characters'||workspace==='classes')&&<><div className="character-roster" aria-label="Select a character">{state.heroes.map(hero=><button key={hero.id} aria-pressed={hero.id===h.id} className={character(p,hero.id).faction} onClick={()=>selectHero(hero.id)}><HeroPortrait id={hero.id} small/><span><strong>{character(p,hero.id).name.split(' ')[0]}</strong><small>{character(p,hero.id).classId} · {bots.includes(hero.id)?'AI':'Player'}</small></span><b>{hero.level}</b></button>)}</div>{workspace==='characters'?<CharacterSheet key={h.id} hero={h} legal={legal} inspect={inspect} open={openAction}/>:<ClassDeck key={h.id} hero={h} inspect={inspect} legal={legal} onLearn={()=>openAction('train')} send={send}/>}{extras.length>0&&<section className="sheet-action-powers"><h3>Available special actions</h3>{extras.map((c,i)=><button className="quiet-button" key={i} onClick={()=>send(c)}>{commandLabel(p,c)}</button>)}</section>}{state.tradeWindow&&state.phase==='actions'&&controlled.includes(h.id)&&d.faction===state.faction&&<button className="quiet-button" onClick={()=>openAction('trade')}>Trade with an ally in this region</button>}</>}
   {workspace==='quests'&&<><div className="workspace-intro"><span className="sheet-eyebrow">CALL TO ARMS</span><h3>The faction journals</h3><p>Select a quest to locate it on the map. Open its book for the full objective and rewards. Replacements are drawn after resolving a quest.</p></div><QuestLedger state={state} selected={selectedQuest} onQuest={chooseQuest} onInspect={setQuestInfo}/></>}
   {workspace==='merchant'&&<><div className="workspace-intro"><span className="sheet-eyebrow">LORDAERON MERCHANT</span><h3>Arms for the road ahead.</h3><p>The merchant is open information. Browse at any time; buying and selling require a Town action in a friendly town.</p><div className="merchant-status"><span><GameIcon name="gold"/>{h.gold} gold · {d.name}</span><button className="gold-button" disabled={!can('town')} onClick={()=>openAction('town')}>Visit merchant · 1 action <Icon name="arrow" size={15}/></button></div>{!can('town')&&<p className="shop-availability">{d.faction!==state.faction?'Wait for your faction’s turn.':!controlled.includes(h.id)?'Select a character you control to shop.':!h.actions?'This character has no actions remaining.':'You need an available Town action in a friendly town.'}</p>}</div><div className="merchant-stock">{state.merchant.map((id,i)=><GameCard key={`${id}-${i}`} card={card(p,id)} onClick={()=>inspect(id)}/>)}</div>{!state.merchant.length&&<p>The merchant has no stock. The turn track adds new items.</p>}<div className="item-deck-counts">{Object.entries(state.deckCounts.items).map(([type,n])=><span key={type}><b>{deckSymbol[type]??'★'}</b>{type} deck<strong>{n}</strong></span>)}</div></>}
   {workspace==='encounters'&&<><div className="encounter-overview"><div className="sealed-event-deck"><img className="ability-art card-illustration" src="/assets/event-art/spellbook.webp" alt=""/><span>WORLD EVENTS</span><strong>{state.deckCounts.events}</strong><small>cards remain</small></div><div className="workspace-intro"><span className="sheet-eyebrow">ENCOUNTER DECK / WORLD EVENTS</span><h3>The world takes its turn.</h3><p>Events are drawn automatically on marked turns. The facedown order stays hidden; active events and discarded cards can be inspected here.</p><b>{nextEvent?`Next event: turn ${nextEvent}`:'No further scheduled events.'}</b><p>{state.eventDiscard.length} discarded · {world.length} active</p></div><OverlordCard overlord={boss} count={state.heroes.length as 4|6}/></div><h3 className="panel-section-heading">Active encounters</h3>{world.length?<div className="encounter-cards">{world.map(e=><EventCardView key={e.id} event={e}/>)}</div>:<p className="panel-empty">No world events are active. {state.turn<4?'The first scheduled event is on turn 4.':'Completed events are in the discard pile.'}</p>}<details className="event-discards"><summary>Discard pile · {state.eventDiscard.length} cards</summary><div className="encounter-cards">{state.eventDiscard.map((id,i)=><EventCardView key={`${id}-${i}`} event={p.events.find(e=>e.id===id)!}/>)}</div></details><h3 className="panel-section-heading">The 30-turn campaign</h3><div className="campaign-track-grid">{Array.from({length:30},(_,i)=><div key={i} className={i+1===state.turn?'current':i+1<state.turn?'past':''}><b>{i+1}</b><span>{p.track[i+1]==='event'?'Event':p.track[i+1]?`${deckSymbol[p.track[i+1]]} Merchant`:'Actions'}</span></div>)}</div></>}
   {workspace==='party'&&<div className="party-control-panel"><span className="sheet-eyebrow">WHO ACTS NEXT?</span><h3>{factionLabel(state.faction)} is on turn {state.turn}.</h3><p>{botReason||'Every character takes two actions. Characters of the active faction can act in any order.'}</p><div className="party-control-list">{state.heroes.map(hero=><button key={hero.id} onClick={()=>{selectHero(hero.id);setWorkspace('characters');}}><HeroPortrait id={hero.id} small/><span><strong>{character(p,hero.id).name}</strong><small>{factionLabel(character(p,hero.id).faction)} · {bots.includes(hero.id)?'AI':'Player'}</small></span><b>{hero.actions}/2 actions</b></button>)}</div><div className="bot-control"><button className="gold-button" onClick={toggleBots}>{auto?'Pause bots':'Run bots'}</button><button className="quiet-button" disabled={!botReady} onClick={botStep}>One bot move <Icon name="right"/></button></div></div>}
  </div></Modal>}
 </div>;
}
