import { useState } from 'react';
import { BASE_PACK as p } from '../data/base';
import { capacity, card, character, faction } from '../rules/common';
import { heroSlots } from '../rules/inventory';
import { commandLabel } from '../rules/legal';
import type { Command, Hero } from '../rules/model';
import type { GameView } from '../rules/view';
import { Icon, ResourceBar } from '../components';
import Map from './Map';
import { AbilityArt, FactionCrest, cardIllustration } from './Art';
import { HeroPortrait, factionLabel } from './parts';
import { BossPortrait, CreatureGlyph } from './design-system';
import { deckSymbol, eventText, overlordText, regionName, rewardText } from './event-text';
export type TablePanel='rest'|'train'|'town'|'challenge'|'manage'|'trade';
export default function Tabletop({state,h,legal,controlled,bots,auto,botReady,botReason,selectHero,selected,selectRegion,inspect,open,send,botStep,toggleBots,focused,toggleFocus,notify}:{state:GameView;h:Hero;legal:Command[];controlled:string[];bots:string[];auto:boolean;botReady:boolean;botReason:string;selectHero:(id:string)=>void;selected:string;selectRegion:(id:string)=>void;inspect:(id:string)=>void;open:(p:TablePanel)=>void;send:(c:Command)=>void;botStep:()=>void;toggleBots:()=>void;focused:boolean;toggleFocus:()=>void;notify:(s:string)=>void}){
 const [inventory,setInventory]=useState<'slots'|'bag'|'talents'>('slots');
 const d=character(p,h.id),cap=capacity(p,h),boss=p.overlords.find(o=>o.id===state.overlord.id)!,stats=boss.stats[state.heroes.length as 4|6];
 const can=(type:Command['type'])=>legal.some(c=>c.type===type&&(!('hero'in c)||c.hero===h.id));
 const extras=legal.filter(c=>'hero'in c&&c.hero===h.id&&['power-action','portal','summon','purify','peek','ability'].includes(c.type));
 const world=(state.world??[]).map(w=>({w,e:p.events.find(e=>e.id===w.id)!}));
 const itemButton=(id:string,key=id)=><button className="satchel-card" key={key} onClick={()=>inspect(id)}><AbilityArt icon={cardIllustration(card(p,id))}/><span><strong>{card(p,id).name}</strong><small>{card(p,id).type} · nivo {card(p,id).level}</small></span></button>;
 return <div className="war-table">
  <aside className="quest-ledger table-frame"><div className="ledger-heading"><Icon name="scroll"/><span>POZIV NA ORUŽJE<small>Questovi Lordaerona</small></span></div>{(['horde','alliance'] as const).map(f=><section className={`faction-quests ${f}`} key={f}><header><FactionCrest faction={f}/><h3>{factionLabel(f)}</h3><span>{state.heroes.filter(h=>faction(p,h.id)===f).reduce((n,h)=>n+h.xp,0)} XP</span></header>{state.quests.map(id=>p.quests.find(q=>q.id===id)!).filter(q=>q.faction===f).map(q=>{const objective=q.spawns.find(s=>s.color!=='blue')!;const remaining=state.enemies.filter(e=>e.quest===q.id&&e.color!=='blue').length;return <button className={`table-quest ${q.tier} ${selected===objective.region?'selected':''}`} key={q.id} title={`${q.spawns.filter(s=>s.color!=='blue').map(s=>`${s.count} × ${s.creature} — ${regionName(s.region)}`).join('\n')}\nNagrada: ${rewardText(q.reward)}`} onClick={()=>selectRegion(objective.region)}><span className="quest-seal"><CreatureGlyph type={objective.creature}/><b>{q.level}</b></span><span><strong>{q.name}</strong><small>{regionName(objective.region)} · {remaining} meta</small><em>{q.reward.xp} XP · {q.reward.gold} zlata {q.reward.items.map(i=>` · ${i.draw}${deckSymbol[i.deck]}`).join('')}{q.reward.special?.length?' · ✦':''}</em></span></button>;})}</section>)}<div className="ledger-foot"><Icon name="check" size={13}/>{state.completed.length} dovršenih questova</div></aside>
  <section className="table-map-column"><button className="boss-ribbon table-frame" title={overlordText(boss)} onClick={()=>selectRegion(state.overlord.region||state.kazzak?.[0]?.region||h.location)}><BossPortrait id={boss.id}/><span><small>PRIJETNJA LORDAERONU</small><strong>{boss.name}</strong><em>{state.overlord.region?regionName(state.overlord.region):'Pet tragova. Jedan demon.'}</em></span><span className="boss-ribbon-stats"><b>{stats.threat+state.overlord.threat}+<small>PRIJETNJA</small></b><b>{stats.attack+state.overlord.attack}<small>NAPAD</small></b><b>{stats.health+state.overlord.health}<small>ZDRAVLJE</small></b></span><Icon name="crown"/></button>
   <Map state={state} heroId={h.id} selected={selected} legal={legal} focused={focused} onToggleFocus={toggleFocus} onSelect={selectRegion} onMove={send}/>
   <div className="action-dock">{([['travel','Putovanje','travel'],['rest','Odmor','rest'],['train','Trening','train'],['town','Grad','town'],['challenge','Izazov','melee']] as const).map(([type,label,icon],i)=><button key={type} disabled={!can(type)} onClick={()=>type==='travel'?notify('Izaberi regiju na mapi, zatim potvrdi putovanje.'):open(type)}><kbd>{i+1}</kbd><AbilityArt icon={icon}/><span>{label}</span></button>)}</div>
   {world.length>0&&<div className="world-ribbon">{world.map(({w,e})=><button key={w.id} title={eventText(e)} onClick={()=>{if(e.boss)selectRegion(e.boss.region);else if(e.script==='plague'&&w.tokens.length)selectRegion(w.tokens[0]);else notify(eventText(e));}}><Icon name={e.boss?'skull':e.script==='plague'?'flask':'scroll'} size={13}/>{e.name}{e.boss?<b>{e.boss.stats.threat}+</b>:null}</button>)}</div>}
  </section>
  <aside className="hero-command table-frame"><div className="party-tabs">{state.heroes.map(hero=><button key={hero.id} title={`${character(p,hero.id).name} · ${bots.includes(hero.id)?'AI':'Igrač'}`} aria-label={character(p,hero.id).name} className={`${hero.id===h.id?'active':''} ${faction(p,hero.id)}`} onClick={()=>selectHero(hero.id)}><HeroPortrait id={hero.id} small/><span>{hero.actions}</span>{bots.includes(hero.id)&&<i>AI</i>}</button>)}</div>
   <section className={`table-hero ${d.faction}`}><div className="hero-banner"><HeroPortrait id={h.id}/><b className="level-coin">{h.level}</b><FactionCrest faction={d.faction}/></div><div className="hero-name"><span className="eyebrow">{d.race} · {d.classId}</span><h2>{d.name}</h2><p><Icon name="pin" size={12}/>{regionName(h.location)}{bots.includes(h.id)?' · AI':''}</p></div><ResourceBar type="health" value={h.health} max={cap.health}/><ResourceBar type="energy" value={h.energy} max={cap.energy}/><div className="hero-counters"><span><Icon name="coins"/>{h.gold}<small>ZLATO</small></span><span><Icon name="spark"/>{h.xp}<small>XP {h.level<5?`/ ${p.xp[h.level]}`:'· MAX'}</small></span><span><Icon name="walk"/>{h.actions}<small>AKCIJE</small></span></div>{(h.curse>0||h.stun>0)&&<p className="afflictions">Curse {h.curse} · Stun {h.stun}</p>}{d.racial&&<button className="racial-button" onClick={()=>inspect(d.racial!)}><Icon name="spark" size={13}/>{card(p,d.racial).name}<Icon name="right" size={12}/></button>}
   <div className="hero-management"><button className="quiet-button" disabled={!can('manage')} onClick={()=>open('manage')}><Icon name="shield" size={14}/>Oprema</button><button className="quiet-button" disabled={!state.tradeWindow||state.phase!=='actions'||!controlled.includes(h.id)||d.faction!==state.faction} onClick={()=>open('trade')}>Razmjena</button></div>
   {extras.length>0&&<details className="extra-actions"><summary>Posebne sposobnosti <b>{extras.length}</b></summary>{extras.map((c,i)=><button key={i} onClick={()=>send(c)}>{commandLabel(p,c)}</button>)}</details>}
   </section><div className="table-ai"><div className="section-row"><h3><Icon name="users" size={14}/>Družina</h3><span>{bots.length} AI</span></div><p title={botReason}>{botReason||'Tvoji saveznici i protivnici čekaju zapovijed.'}</p><div className="bot-control"><button className={auto?'gold-button':'quiet-button'} onClick={toggleBots}>{auto?'Pauziraj botove':'Pokreni botove'}<Icon name={auto?'minus':'arrow'} size={14}/></button><button className="icon-button" aria-label="Jedan potez botova" title="Jedan potez botova" disabled={!botReady} onClick={botStep}><Icon name="right"/></button></div></div>
  </aside>
  <section className="player-mat table-frame"><header><div><FactionCrest faction={d.faction}/><span><strong>{d.name.split(' ')[0]}</strong><small>LIČNI LIST</small></span></div><nav>{([['slots','Oprema',heroSlots(p,h).length],['bag','Torba',h.bag.length],['talents','Talenti',h.talents.length]] as const).map(([id,label,n])=><button key={id} className={inventory===id?'active':''} onClick={()=>setInventory(id)}>{label}<b>{n}</b></button>)}</nav><button className="quiet-button" disabled={!can('manage')} onClick={()=>open('manage')}>Upravljaj <Icon name="shield" size={12}/></button></header>
   {inventory==='slots'?<div className="seven-slots">{heroSlots(p,h).map((slot,i)=>{const id=h.slots[i]?.card??slot.printed;return <div className={`mat-slot ${id?'filled':''}`} key={i}><span className="slot-label">{i+1}<small>{slot.stanceOnly?'STANCE':slot.types.join(' / ')}</small></span>{id?<button className="slot-card" onClick={()=>inspect(id)}><AbilityArt icon={cardIllustration(card(p,id))}/><strong>{card(p,id).name}</strong><span>{card(p,id).printed?'Početna karta':`Nivo ${card(p,id).level}`}<b><Icon name="bolt" size={11}/>{card(p,id).energy}</b></span></button>:<button className="empty-slot" disabled={!can('manage')} onClick={()=>open('manage')}><Icon name={slot.types.includes('active')?'spark':slot.types.includes('melee')?'sword':'layers'} size={22}/><span>Prazno mjesto</span></button>}{h.slots[i]?.addons.map(id=><button key={id} className="slot-addon" onClick={()=>inspect(id)}>+ {card(p,id).name}</button>)}</div>;})}</div>:<div className="satchel-list">{(inventory==='bag'?h.bag:h.talents).map(id=>itemButton(id))}{(inventory==='bag'?h.bag:h.talents).length===0&&<p>{inventory==='bag'?'Torba je prazna. Predmete dobijaš iz questova ili kod trgovca.':'Talente biraš kada dostigneš novi nivo.'}</p>}{inventory==='bag'&&h.auctionItems.map(id=>itemButton(id,`auction-${id}`))}</div>}
  </section>
  <div className="table-turn-track"><span>SMJENA<big>{state.turn}<small>/ 30</small></big></span><div>{Array.from({length:30},(_,i)=><span key={i} className={`${i+1===state.turn?'current':''} ${i+1<state.turn?'past':''}`} title={`${i+1}. smjena${p.track[i+1]?` · ${p.track[i+1]==='event'?'događaj':`trgovac ${deckSymbol[p.track[i+1]]}`}`:''}`}><b>{i+1}</b><small>{p.track[i+1]==='event'?'◆':deckSymbol[p.track[i+1]]??'·'}</small></span>)}<Icon name="swords" size={22}/></div></div>
 </div>;
}
