import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {BASE_PACK as p,DEFAULT_SETUP} from '../src/data/base';
import Campaign from '../src/Campaign';
import Combat from '../src/campaign/Combat';
import {GameCard,CharacterCard} from '../src/campaign/parts';
import CharacterSheet,{startingHero} from '../src/campaign/CharacterSheet';
import CampaignSetup from '../src/campaign/CampaignSetup';
import {CreatureCard,EventCardView,OverlordCard,QuestCard} from '../src/campaign/design-system';
import {createGame} from '../src/rules/game';
import {beginBattle,chooseAttacker} from '../src/rules/combat';
import {legalActions} from '../src/rules/legal';
import {view} from '../src/rules/view';
let count=0;const render=(component:React.ReactElement)=>{const html=renderToStaticMarkup(component);if(html.includes('undefined')||html.includes('NaN'))throw new Error(`Invalid content in ${component.type}`);count++;};
for(const card of p.cards)render(React.createElement(GameCard,{card}));
for(const c of p.characters)render(React.createElement(CharacterCard,{id:c.id}));
for(const c of p.characters)render(React.createElement(CharacterSheet,{hero:startingHero(c.id),inspect:()=>{},preview:true}));
render(React.createElement(CampaignSetup,{onStart:()=>{},onCancel:()=>{}}));
for(const creature of p.creatures)render(React.createElement(CreatureCard,{creature}));
for(const quest of p.quests)render(React.createElement(QuestCard,{quest}));
for(const event of p.events)render(React.createElement(EventCardView,{event}));
for(const overlord of p.overlords)render(React.createElement(OverlordCard,{overlord}));
render(React.createElement(Campaign));
const s=createGame(p,DEFAULT_SETUP);s.enemies=[{id:'smoke',creature:'murloc',color:'blue',region:'brill'}];beginBattle(s,'pve',[s.heroes[0].id],['smoke'],'horde','brill');chooseAttacker(p,s,s.heroes[0].id);
render(React.createElement(Combat,{state:view(s),legal:legalActions(p,s),send:()=>{},busy:false,botStep:()=>{},botReady:false,auto:false,toggleBots:()=>{}}));
console.log(JSON.stringify({rendered:count,pack:p.id,invalidText:false}));
