import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { BASE_PACK as p, DEFAULT_SETUP, CONTENT_COVERAGE } from './data/base';
import { capacity, card, character, faction } from './rules/common';
import { apply, createGame } from './rules/game';
import { legalActions } from './rules/legal';
import { importSession, newSession } from './rules/session';
import { view } from './rules/view';
import type { Command, Setup } from './rules/model';
import { decide, type Difficulty } from './ai/planner';
import { botOwns, decisionOwners } from './multiplayer/ownership';
import { Icon, Modal } from './components';
import { TownEditor, EquipmentEditor, TradeEditor } from './campaign/Interactions';
import { GameCard, HeroPortrait, CharacterCard, factionLabel, phaseLabel } from './campaign/parts';
import { effectText, conditionText, staticCardText } from './campaign/rules-text';
import { triggerLabels, BossPortrait, CreatureGlyph } from './campaign/design-system';
import { FactionCrest } from './campaign/Art';
import { bossRules, regionName } from './campaign/event-text';
import Tabletop, { type TablePanel } from './campaign/Tabletop';
import BaseCatalog from './campaign/BaseCatalog';
import WorldDecision from './campaign/WorldDecision';
const CampaignCombat=lazy(()=>import('./campaign/Combat'));
const DesignGallery=lazy(()=>import('./campaign/DesignGallery'));
const SAVE='lordaeron-base-save-v3',BOTS='lordaeron-base-bots-v3';
type Panel=TablePanel|'new'|'settings'|'card'|null;
function load(){try{const raw=localStorage.getItem(SAVE);if(raw){try{return importSession(p,raw);}catch{localStorage.setItem(`${SAVE}-recovery-${Date.now()}`,raw);}}}catch{/* File export also works without browser storage. */}return{state:createGame(p,DEFAULT_SETUP),session:newSession(p,DEFAULT_SETUP)};}
export default function Campaign(){
 const[game,setGame]=useState(load),[page,setPage]=useState('board'),[panel,setPanel]=useState<Panel>(null),[heroId,setHeroId]=useState(DEFAULT_SETUP.roster[0]),[selected,setSelected]=useState('brill'),[toast,setToast]=useState(''),[detailCard,setDetailCard]=useState(p.cards[0].id);
 const[bots,setBots]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem(BOTS)??'null');return Array.isArray(value)?value:DEFAULT_SETUP.roster.slice(1);}catch{return DEFAULT_SETUP.roster.slice(1);}}),[auto,setAuto]=useState(false),[difficulty,setDifficulty]=useState<Difficulty>('balanced'),[botReason,setBotReason]=useState('');
 const[restHP,setRestHP]=useState(0),[food,setFood]=useState(''),[training,setTraining]=useState<string[]>([]),[exportJSON,setExportJSON]=useState(''),[roster,setRoster]=useState(DEFAULT_SETUP.roster),[seed,setSeed]=useState('2005'),[overlord,setOverlord]=useState(DEFAULT_SETUP.overlord),[newBots,setNewBots]=useState(true),[human,setHuman]=useState(DEFAULT_SETUP.roster[0]),[mapFocus,setMapFocus]=useState(false);
 const file=useRef<HTMLInputElement>(null),current=useRef(game);current.current=game;
 const controlled=game.state.heroes.filter(h=>!bots.includes(h.id)).map(h=>h.id);
 const state=view(game.state,controlled),allLegal=useMemo(()=>legalActions(p,game.state),[game.state]);
 const legal=allLegal.filter(c=>decisionOwners(p,state,c).some(id=>controlled.includes(id)));
 const h=state.heroes.find(h=>h.id===heroId)??state.heroes[0],definition=character(p,h.id),cap=capacity(p,h);
 const can=(type:Command['type'])=>legal.some(c=>c.type===type&&(!('hero'in c)||c.hero===h.id));
 const nextPhase=legal.find(c=>c.type==='endActions'||c.type==='endManagement');
 const botReady=allLegal.some(c=>botOwns(p,game.state,c,bots));
 useEffect(()=>{try{localStorage.setItem(SAVE,JSON.stringify(game.session));localStorage.setItem(BOTS,JSON.stringify(bots));}catch{setToast('Automatsko čuvanje nije dostupno. Izvezi kopiju partije u postavkama.');}},[game,bots]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),8000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const next=state.heroes.find(h=>faction(p,h.id)===state.faction&&controlled.includes(h.id))??state.heroes.find(h=>faction(p,h.id)===state.faction);if(next){setHeroId(next.id);setSelected(next.location);}},[state.faction]);
 useEffect(()=>{window.scrollTo(0,0);},[page]);
 const send=(c:Command)=>{try{const before=current.current;const next={state:apply(p,before.state,c),session:{...before.session,commands:[...before.session.commands,c]}};current.current=next;setGame(next);return true;}catch(e){setToast((e as Error).message);return false;}};
 const botStep=()=>{const candidates=allLegal.filter(c=>botOwns(p,game.state,c,bots));const decision=decide(p,view(game.state,bots),candidates,difficulty);if(decision){setBotReason(decision.reason);send(decision.command);}else setToast('Sada je na redu ljudski igrač.');};
 useEffect(()=>{if(!auto||!botReady)return;const t=setTimeout(botStep,550);return()=>clearTimeout(t);},[auto,botReady,game.state.revision,bots,difficulty]);
 const chooseHero=(id:string)=>{setHeroId(id);setSelected(state.heroes.find(h=>h.id===id)!.location);};
 const open=(next:Panel)=>{if(next==='rest'){setFood('');setRestHP(Math.max(0,Math.min(cap.health-h.health,h.level*(['both',state.faction].includes(p.regions.find(r=>r.id===h.location)?.town??'')?3:2))));}if(next==='train')setTraining([]);setPanel(next);};
 const inspect=(id:string)=>{setDetailCard(id);setPanel('card');};
 const closeAfter=(c:Command)=>{if(send(c))setPanel(null);};
 const reset=(setup:Setup)=>{try{const state=createGame(p,setup);const next={state,session:newSession(p,setup)};current.current=next;setGame(next);const humanId=setup.roster.includes(human)?human:setup.roster[0];setBots(newBots?setup.roster.filter(id=>id!==humanId):[]);setHeroId(humanId);setSelected(state.heroes.find(h=>h.id===humanId)!.location);setAuto(false);setBotReason('');setPanel(null);setPage('board');}catch(e){setToast((e as Error).message);}};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey||(e.target as HTMLElement).closest('input,select,textarea,dialog,[contenteditable=true]')||panel)return;const action=(['travel','rest','train','town','challenge'] as const)[Number(e.key)-1];if(action&&page==='board'&&can(action)){e.preventDefault();if(action==='travel')setToast('Odaberi dostupnu regiju na mapi.');else open(action);}if(e.key.toLowerCase()==='f'&&page==='board')setMapFocus(v=>!v);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 const exportSave=()=>{const raw=JSON.stringify(game.session,null,2);setExportJSON(raw);const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`lordaeron-${game.state.turn}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
 const importFile=async(f?:File)=>{if(!f)return;try{const next=importSession(p,await f.text());current.current=next;setGame(next);setBots([]);setAuto(false);setHeroId(next.state.heroes[0].id);setSelected(next.state.heroes[0].location);setPanel(null);setToast('Partija je provjerena ponavljanjem svih poteza.');}catch(e){setToast((e as Error).message);}if(file.current)file.current.value='';};
 const title=panel==='new'?'Nova kampanja':panel==='settings'?'Tvoja partija':panel==='rest'?'Odmor':panel==='train'?'Trening':panel==='town'?'Gradska tržnica':panel==='challenge'?'Izaberi izazov':panel==='manage'?'Upravljanje likom':panel==='trade'?'Razmjena sa saveznikom':card(p,detailCard).name;
 const decision=(state.phase==='reward'||!!state.auction||!!state.eventFlow?.steps.length||state.heroes.some(h=>h.talentChoices.length)||state.respawns.length>0)&&state.phase!=='combat';
 return <div className={`campaign-app ${page==='board'?'desktop-tabletop':''} ${mapFocus?'map-focus':''}`}>
 <header className="topbar"><button className="wordmark" onClick={()=>setPage('board')}><span className="brand-crest"><Icon name="swords" size={29}/></span><span><strong>WORLD <small>of</small> WARCRAFT</strong><em>THE BOARD GAME <i/> 2005 + FAQ</em></span></button><nav className="topnav">{[['board','Kampanja'],['cards','Knjiga karata'],['heroes','Junaci'],['journal','Hronika'],['rules','Pravila']].map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><div className="header-right"><span className="session-badge"><i/>LOKALNA PARTIJA</span><button className="icon-button" aria-label="Nova partija" onClick={()=>open('new')}><Icon name="plus"/></button><button className="icon-button" aria-label="Postavke" onClick={()=>open('settings')}><Icon name="settings"/></button></div></header>
 <main className="campaign-main"><div className="campaign-title"><div><div className="eyebrow"><span className="chapter-dot"/>LORDAERON <span className="slash">/</span> RAT DVIJU FRAKCIJA</div><h1>Sudbina kraljevstva<span>{phaseLabel[state.phase]}</span></h1></div><div className="campaign-turn"><FactionCrest faction={state.faction}/><span className={state.faction}>{factionLabel(state.faction)}</span><b>{state.turn}<small> / 30</small></b><button className="quiet-button" disabled={!nextPhase} onClick={()=>nextPhase&&send(nextPhase)}>{state.phase==='actions'?'Upravljanje':'Završi smjenu'}<Icon name="arrow"/></button></div></div>
 {page==='board'&&<Tabletop state={state} h={h} legal={legal} controlled={controlled} bots={bots} auto={auto} botReady={botReady} botReason={botReason} selectHero={chooseHero} selected={selected} selectRegion={setSelected} inspect={inspect} open={open} send={send} botStep={botStep} toggleBots={()=>setAuto(v=>!v)} focused={mapFocus} toggleFocus={()=>setMapFocus(v=>!v)} notify={setToast}/>}
 {page==='cards'&&<BaseCatalog inspect={inspect}/>}
 {page==='heroes'&&<div className="character-gallery">{p.characters.map(c=><CharacterCard key={c.id} id={c.id}/>)}</div>}
 {page==='design'&&<Suspense fallback={<p>Učitavanje…</p>}><DesignGallery/></Suspense>}
 {page==='journal'&&<section className="journal-page"><span className="eyebrow">HRONIKA LORDAERONA</span><h2>Priča tvoje družine</h2>{[...state.log].reverse().map(l=><article key={l.id}><span>SMJENA {l.turn}</span><p>{p.characters.reduce((text,c)=>text.replaceAll(c.id,c.name),l.text)}</p></article>)}</section>}
 {page==='rules'&&<section className="coverage-page"><span className="eyebrow">OSNOVNA IGRA 2005 + FAQ 1.4</span><h2>Pravila za tvoj sto</h2><div className="rules-grid"><article><h3>Dvije akcije po liku</h3><p>Likovi aktivne frakcije raspoređuju akcije bilo kojim redom: Travel, Rest, Train, Town i Challenge. Nakon akcija slijedi zajednička faza upravljanja opremom.</p></article><article><h3>Borba u koracima</h3><p>Izaberi napadača, pripremi i baci kockice, odigraj reroll i sposobnosti, postavi pogotke, podijeli rane i razriješi borbu. Sposobnosti se nude u trenutku kada su dozvoljene.</p></article><article><h3>Pobjeda</h3><p>Porazi izabranog Overlorda ili pobijedi u završnom PvP-u nakon 30. smjene. Nefarian može ranije izazvati završnicu dolaskom u Bulwark.</p></article><article><h3>AI i lokalna partija</h3><p>Botovi koriste isti engine i dozvoljene poteze. Ne vide redoslijed špilova, buduća bacanja ni skrivene Kazzakove tragove protivničke frakcije. Online sobe su na čekanju.</p></article></div><table><thead><tr><th>Sadržaj</th><th>Broj</th><th>Uvezeno iz skenova</th></tr></thead><tbody>{CONTENT_COVERAGE.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.expected}</td><td>{c.note}</td></tr>)}</tbody></table><p className="coverage-note">Mapa ima {p.regions.length} regija prenesenih s fotografije fizičke ploče. Dostavljeni arhiv ne sadrži ravan sken glavne ploče; veze i letne oznake još treba uporediti s njim. Izvorne slike čuvaju se lokalno, a interfejs koristi nove ilustracije i predloške. Automatski testovi provjeravaju ključne interakcije; dodatno igranje je potrebno za preostale rubne kombinacije.</p><div className="sources-list"><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/wowrules.pdf" target="_blank" rel="noreferrer">Službeni pravilnik <Icon name="arrow"/></a><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/WoW_FAQ__v1_4.pdf" target="_blank" rel="noreferrer">FAQ / errata <Icon name="arrow"/></a><button className="quiet-button" onClick={()=>setPage('design')}>Dizajn sistem</button></div></section>}
 </main>
 {toast&&<div className="toast" role="status"><Icon name="help"/>{toast}<button className="icon-button" aria-label="Zatvori obavijest" onClick={()=>setToast('')}><Icon name="x" size={14}/></button></div>}
 {state.battle&&state.phase==='combat'&&<Suspense fallback={<p>Priprema borbe…</p>}><CampaignCombat state={state} legal={legal} busy={false} send={send} botStep={botStep} botReady={botReady} auto={auto} toggleBots={()=>setAuto(v=>!v)}/></Suspense>}
 {decision&&<WorldDecision key={`${state.phase}-${state.eventFlow?.event}-${state.eventFlow?.steps[0]?.hero}-${state.heroes.find(h=>h.talentChoices.length)?.id}-${state.reward?.offered.join()}`} state={state} legal={legal} send={send} inspect={inspect} botStep={botStep} botReady={botReady} auto={auto} toggleBots={()=>setAuto(v=>!v)}/>}
 {state.phase==='finished'&&<div className="victory-strip"><Icon name="trophy" size={38}/><h2>{state.winner==='draw'?'Kampanja završava neriješeno':`${factionLabel(state.winner??'')} pobjeđuje!`}</h2><p>{state.turn}. smjena</p><button className="gold-button" onClick={()=>open('new')}>Nova kampanja</button></div>}
 <input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>void importFile(e.target.files?.[0])}/>
 {panel&&<Modal title={title} wide={['new','town','manage','trade','train'].includes(panel)} onClose={()=>setPanel(null)}>
 {panel==='rest'&&<div className="dialog-content"><p>Prijateljski grad: 3 × nivo. Divljina: 2 × nivo. Odmor uklanja Curse.</p><label className="rest-slider">Zdravlje: <b>{restHP}</b><input type="range" min={0} max={Math.max(0,Math.min(cap.health-h.health,h.level*(['both',state.faction].includes(p.regions.find(r=>r.id===h.location)?.town??'')?3:2)))} value={restHP} onChange={e=>setRestHP(Number(e.target.value))}/></label><p>Preostali oporavak ide u energiju, do kapaciteta lika.</p><label className="setting-row">Hrana<select value={food} onChange={e=>setFood(e.target.value)}><option value="">Bez hrane</option>{[...new Set(legal.filter(c=>c.type==='rest'&&c.hero===h.id&&c.food).map(c=>c.type==='rest'?c.food!:''))].map(id=><option key={id} value={id}>{card(p,id).name}</option>)}</select></label><button className="gold-button" onClick={()=>closeAfter({type:'rest',hero:h.id,health:restHP,food:food||undefined})}>Odmori · 1 akcija</button></div>}
 {panel==='train'&&<div className="dialog-content"><p>Odaberi moći koje želiš naučiti za jednu akciju. Opremi ih u fazi upravljanja.</p><div className="game-card-grid">{p.cards.filter(c=>c.kind==='power'&&!c.printed&&c.classId===definition.classId).map(c=><GameCard key={c.id} card={c} selected={training.includes(c.id)} disabled={h.learned.includes(c.id)||c.level>h.level} onClick={()=>setTraining(v=>v.includes(c.id)?v.filter(id=>id!==c.id):[...v,c.id])}/>)}</div><button className="gold-button full-width sticky-confirm" disabled={!training.length||training.reduce((n,id)=>n+card(p,id).price,0)>h.gold} onClick={()=>closeAfter({type:'train',hero:h.id,cards:training})}>Nauči · {training.reduce((n,id)=>n+card(p,id).price,0)} / {h.gold} zlata</button></div>}
 {panel==='town'&&<TownEditor hero={h} merchant={state.merchant} busy={false} send={closeAfter}/>}
 {panel==='manage'&&<EquipmentEditor hero={h} busy={false} send={closeAfter}/>}
 {panel==='trade'&&<TradeEditor hero={h} heroes={state.heroes} busy={false} send={closeAfter}/>}
 {panel==='challenge'&&<div className="dialog-content"><p>Svaki pozvani saveznik troši jednu akciju. Plava stvorenja imaju prioritet.</p><div className="challenge-list">{legal.filter((c):c is Extract<Command,{type:'challenge'}>=>c.type==='challenge'&&c.hero===h.id).map((c,i)=>{const e=state.enemies.find(e=>e.id===c.target),creature=p.creatures.find(a=>a.id===e?.creature);const name=creature?.name??p.events.find(e=>e.id===c.target)?.name??p.overlords.find(o=>o.id===c.target)?.name??(c.target==='pvp'?'Protivnička družina':'Kazzakov trag');return <button key={i} className="merchant-row" onClick={()=>closeAfter(c)}>{creature?<CreatureGlyph type={creature.rule}/>:<Icon name="swords" size={30}/>}<span><strong>{name}</strong><small>{c.region?`${regionName(c.region)} · Intercept · `:''}{c.allies.length?c.allies.map(id=>character(p,id).name.split(' ')[0]).join(' + '):'Samostalni izazov'}</small></span><Icon name="arrow"/></button>;})}</div></div>}
 {panel==='card'&&<div className="card-detail"><GameCard card={card(p,detailCard)}/><div><h3>{card(p,detailCard).name}</h3><p>Nivo {card(p,detailCard).level} · {card(p,detailCard).trait||card(p,detailCard).type} · {card(p,detailCard).energy} energije</p>{card(p,detailCard).abilities.map(a=><p key={a.id}><b>{triggerLabels[a.timing]??a.timing}{a.automatic?' · automatski':''}{a.cost!==undefined?` · ${a.cost} energije`:''}</b><br/>{a.condition?`Ako ${conditionText(a.condition)}: `:''}{a.effects.map(effectText).join(' · ')}</p>)}{staticCardText(card(p,detailCard)).map(t=><p key={t}>{t}</p>)}<a className="source-link" href={card(p,detailCard).source.url} target="_blank" rel="noreferrer">Izvorna karta ↗</a></div></div>}
 {panel==='settings'&&<div className="dialog-content"><div className="settings-buttons"><button className="quiet-button" onClick={exportSave}><Icon name="download"/>Izvezi partiju</button><button className="quiet-button" onClick={()=>file.current?.click()}><Icon name="upload"/>Uvezi partiju</button></div>{exportJSON&&<textarea className="save-text" value={exportJSON} readOnly aria-label="Kopija partije" onFocus={e=>e.target.select()}/>}<label className="setting-row">Stil botova<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="balanced">Uravnotežen</option><option value="cautious">Oprezan</option><option value="aggressive">Agresivan</option></select></label><div className="bot-seats">{state.heroes.map(hero=><label key={hero.id}><HeroPortrait id={hero.id} small/><span>{character(p,hero.id).name}</span><input type="checkbox" checked={bots.includes(hero.id)} onChange={e=>setBots(v=>e.target.checked?[...v,hero.id]:v.filter(id=>id!==hero.id))}/>AI</label>)}</div><button className="gold-button full-width" onClick={()=>open('new')}>Nova kampanja</button><p className="muted">Online sobe su na čekanju. Lokalna partija se automatski čuva u ovom pregledniku.</p></div>}
 {panel==='new'&&<div className="dialog-content"><p>Četiri ili šest likova, jednak broj po frakciji. Svaka klasa smije biti odabrana samo jednom.</p><div className="boss-selection">{p.overlords.map(o=><button key={o.id} className={o.id===overlord?'selected':''} onClick={()=>setOverlord(o.id)} title={bossRules[o.combat]}><BossPortrait id={o.id}/><strong>{o.name}</strong><small>{o.id==='kazzak'?'Lov na skrivenog demona':o.id==='nefarian'?'Trka prema Bulwarku':'Kuga i Scourge događaji'}</small></button>)}</div><div className="setup-count"><button className={roster.length===4?'selected':''} onClick={()=>setRoster([...DEFAULT_SETUP.roster.slice(0,2),...DEFAULT_SETUP.roster.slice(3,5)])}>4 lika</button><button className={roster.length===6?'selected':''} onClick={()=>setRoster(DEFAULT_SETUP.roster)}>6 likova</button><label><input type="checkbox" checked={newBots} onChange={e=>setNewBots(e.target.checked)}/>Popuni AI igračima</label></div><div className="setup-roster">{(['horde','alliance'] as const).map(f=><section key={f}><h3 className={f}><FactionCrest faction={f}/>{factionLabel(f)}</h3>{p.characters.filter(c=>c.faction===f).map(c=><button key={c.id} className={roster.includes(c.id)?'selected':''} onClick={()=>setRoster(v=>v.includes(c.id)?v.filter(id=>id!==c.id):[...v.filter(id=>character(p,id).classId!==c.classId),c.id])}><HeroPortrait id={c.id} small/><span>{c.name}<small>{c.classId}</small></span>{roster.includes(c.id)&&<Icon name="check"/>}</button>)}</section>)}</div>{newBots&&<label className="setting-row">Tvoj lik<select value={roster.includes(human)?human:roster[0]??''} onChange={e=>setHuman(e.target.value)}>{roster.map(id=><option key={id} value={id}>{character(p,id).name}</option>)}</select></label>}<details className="seed-options"><summary>Napredne postavke</summary><label className="seed-label">Broj za ponovljivu partiju<input value={seed} onChange={e=>setSeed(e.target.value)} inputMode="numeric"/></label></details><button className="gold-button full-width" onClick={()=>reset({seed:Number(seed),roster,overlord})}>Započni kampanju <Icon name="arrow"/></button></div>}
 </Modal>}
 </div>;
}
