import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { BASE_PACK as p, DEFAULT_SETUP, CONTENT_COVERAGE } from './data/base';
import { capacity, card, character, faction } from './rules/common';
import { apply, createGame } from './rules/game';
import { legalActions } from './rules/legal';
import { importSession, newSession } from './rules/session';
import { view } from './rules/view';
import type { Command, Setup } from './rules/model';
import { type Difficulty } from './ai/planner';
import { PlannerClient } from './ai/client';
import { botOwns, decisionOwners } from './multiplayer/ownership';
import { Icon, Modal } from './components';
import { TownEditor, EquipmentEditor, TradeEditor } from './campaign/Interactions';
import { GameCard, HeroPortrait, factionLabel, phaseLabel } from './campaign/parts';
import { CreatureGlyph } from './campaign/design-system';
import { FactionCrest } from './campaign/Art';
import { regionName } from './campaign/event-text';
import Tabletop, { type TablePanel } from './campaign/Tabletop';
import BaseCatalog from './campaign/BaseCatalog';
import ClassDeck from './campaign/ClassDeck';
import WorldDecision from './campaign/WorldDecision';
import CampaignSetup from './campaign/CampaignSetup';
import CharacterSheet, { CardRules, startingHero } from './campaign/CharacterSheet';
import { combatCandidates, COMBAT_STEP_MS, DICE_SETTLE_MS, rollSignature } from './campaign/combat-flow';
import { challengeProfile, ThreatLevel } from './campaign/feedback';
const CampaignCombat=lazy(()=>import('./campaign/Combat'));
const DesignGallery=lazy(()=>import('./campaign/DesignGallery'));
const SAVE='lordaeron-base-save-v6',LEGACY_SAVE='lordaeron-base-save-v4',BOTS='lordaeron-base-bots-v3';
function legacy(){try{return localStorage.getItem(LEGACY_SAVE)??localStorage.getItem('lordaeron-base-save-v3');}catch{return null;}}
function previousCampaign(){try{return localStorage.getItem(`${SAVE}-before-new`);}catch{return null;}}
function downloadSession(raw:string,name:string){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
type Panel=TablePanel|'new'|'settings'|'card'|null;
function load():ReturnType<typeof importSession>&{needsSetup?:boolean}{try{const raw=localStorage.getItem(SAVE);if(raw){try{return importSession(p,raw);}catch{localStorage.setItem(`${SAVE}-recovery-${Date.now()}`,raw);}}}catch{/* File export also works without browser storage. */}return{state:createGame(p,DEFAULT_SETUP),session:newSession(p,DEFAULT_SETUP),needsSetup:true};}
export default function Campaign(){
 const[legacySave]=useState(legacy),[previousSave,setPreviousSave]=useState(previousCampaign);
 const[game,setGame]=useState(load),[page,setPage]=useState('board'),[panel,setPanel]=useState<Panel>(()=>game.needsSetup?'new':null),[heroId,setHeroId]=useState(DEFAULT_SETUP.roster[0]),[selected,setSelected]=useState('brill'),[toast,setToast]=useState(()=>{try{return legacySave&&!localStorage.getItem(SAVE)?"Equipment and combat rules have been updated. Your previous game is preserved; download a copy in Settings.":'';}catch{return '';}}),[detailCard,setDetailCard]=useState(p.cards[0].id);
 const[bots,setBots]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem(BOTS)??'null');return Array.isArray(value)?value:DEFAULT_SETUP.roster.slice(1);}catch{return DEFAULT_SETUP.roster.slice(1);}}),[auto,setAuto]=useState(false),[difficulty,setDifficulty]=useState<Difficulty>('balanced'),[botReason,setBotReason]=useState('');
 const[restHP,setRestHP]=useState(0),[food,setFood]=useState(''),[training,setTraining]=useState<string[]>([]),[exportJSON,setExportJSON]=useState(''),[codexHero,setCodexHero]=useState(DEFAULT_SETUP.roster[0]),[mapFocus,setMapFocus]=useState(false);
 const[combatOpen,setCombatOpen]=useState(false),[combatResolve,setCombatResolve]=useState(true),[combatPlay,setCombatPlay]=useState(false),[settledRoll,setSettledRoll]=useState('');
 const file=useRef<HTMLInputElement>(null),current=useRef(game);current.current=game;
 const planner=useRef<PlannerClient|null>(null);
 useEffect(()=>()=>{planner.current?.dispose();planner.current=null;},[bots,difficulty]);
 const controlled=game.state.heroes.filter(h=>!bots.includes(h.id)).map(h=>h.id);
 const state=view(game.state,controlled),allLegal=useMemo(()=>legalActions(p,game.state),[game.state]);
 const legal=allLegal.filter(c=>decisionOwners(p,state,c).some(id=>controlled.includes(id)));
 const h=state.heroes.find(h=>h.id===heroId)??state.heroes[0],cap=capacity(p,h);
 const can=(type:Command['type'])=>legal.some(c=>c.type===type&&(!('hero'in c)||c.hero===h.id));
 const nextPhase=legal.find(c=>c.type==='endActions'||c.type==='endManagement');
 const botReady=allLegal.some(c=>botOwns(p,game.state,c,bots));
 useEffect(()=>{if(game.needsSetup)return;try{localStorage.setItem(SAVE,JSON.stringify(game.session));localStorage.setItem(BOTS,JSON.stringify(bots));}catch{setToast("Autosave is unavailable. Export a copy of your game in Settings.");}},[game,bots]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),8000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const next=state.heroes.find(h=>faction(p,h.id)===state.faction&&controlled.includes(h.id))??state.heroes.find(h=>faction(p,h.id)===state.faction);if(next){setHeroId(next.id);setSelected(next.location);}},[state.faction]);
 useEffect(()=>{window.scrollTo(0,0);},[page]);
 const send=(c:Command)=>{try{const before=current.current;const next={state:apply(p,before.state,c),session:{...before.session,commands:[...before.session.commands,c]}};current.current=next;setGame(next);return true;}catch(e){setToast((e as Error).message);return false;}};
 const planMove=async(candidates:Command[],valid=()=>true)=>{
  const source=current.current.state;
  if(!candidates.length){setToast("A human player acts next.");return;}
  try{
   planner.current??=new PlannerClient();
   const decision=await planner.current.plan(view(source,bots),candidates,difficulty);
   if(decision&&valid()&&current.current.state===source){setBotReason(decision.reason);send(decision.command);}
  }catch(e){if(valid()&&current.current.state===source)setToast((e as Error).message);}
 };
 const botStep=()=>{void planMove(allLegal.filter(c=>botOwns(p,game.state,c,bots)));};
 useEffect(()=>{if(!auto||!botReady||state.phase==='combat')return;let cancelled=false;const t=setTimeout(()=>{void planMove(allLegal.filter(c=>botOwns(p,game.state,c,bots)),()=>!cancelled);},550);return()=>{cancelled=true;clearTimeout(t);};},[auto,botReady,game.state,bots,difficulty]);
 const rollingKey=rollSignature(state),diceRolling=!!rollingKey&&rollingKey!==settledRoll;
 useEffect(()=>{if(!rollingKey){setSettledRoll('');return;}const t=setTimeout(()=>setSettledRoll(rollingKey),DICE_SETTLE_MS);return()=>clearTimeout(t);},[rollingKey]);
 useEffect(()=>{setCombatOpen(state.phase==='combat');if(state.phase!=='combat')setCombatPlay(false);},[state.phase]);
 const automaticCombat=useMemo(()=>combatCandidates(p,state,allLegal,bots,{resolve:combatResolve,play:combatPlay,campaignAuto:auto,difficulty}),[game.state,allLegal,bots,combatResolve,combatPlay,auto,difficulty]);
 useEffect(()=>{if(!automaticCombat.length||diceRolling)return;let cancelled=false;const source=game.state;const t=setTimeout(()=>{if(current.current.state!==source)return;if(automaticCombat.length===1)send(automaticCombat[0]);else void planMove(automaticCombat,()=>!cancelled);},COMBAT_STEP_MS);return()=>{cancelled=true;clearTimeout(t);};},[automaticCombat,diceRolling,game.state]);
 const chooseHero=(id:string)=>{setHeroId(id);setSelected(state.heroes.find(h=>h.id===id)!.location);};
 const open=(next:Panel)=>{if(next==='rest'){setFood('');setRestHP(Math.max(0,Math.min(cap.health-h.health,h.level*(['both',state.faction].includes(p.regions.find(r=>r.id===h.location)?.town??'')?3:2))));}if(next==='train')setTraining([]);setPanel(next);};
 const inspect=(id:string)=>{setDetailCard(id);setPanel('card');};
 const closeAfter=(c:Command)=>{if(send(c)){setPanel(null);if(c.type==='manage')setToast(`${character(p,c.hero).name.split(' ')[0]}’s equipment is ready. Loadout saved.`);if(c.type==='train')setToast('Powers learned. Equip them during equipment management.');}};
 const reset=(setup:Setup,human:string,newBots:boolean)=>{try{const state=createGame(p,setup);if(!game.needsSetup){const backup=JSON.stringify(game.session);setPreviousSave(backup);try{localStorage.setItem(`${SAVE}-before-new`,backup);}catch{/* The in-memory backup remains downloadable. */}}const next={state,session:newSession(p,setup)};current.current=next;setGame(next);const humanId=setup.roster.includes(human)?human:setup.roster[0];setBots(newBots?setup.roster.filter(id=>id!==humanId):[]);setHeroId(humanId);setSelected(state.heroes.find(h=>h.id===humanId)!.location);setAuto(false);setMapFocus(false);setBotReason('');setPanel(null);setPage('board');}catch(e){setToast((e as Error).message);}};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey||(e.target as HTMLElement).closest('input,select,textarea,dialog,[contenteditable=true]')||panel||game.needsSetup||document.querySelector('dialog[open]'))return;const action=(['travel','rest','train','town','challenge'] as const)[Number(e.key)-1];if(action&&page==='board'&&can(action)){e.preventDefault();if(action==='travel')setMapFocus(true);else open(action);}if(e.key.toLowerCase()==='f'&&page==='board')setMapFocus(v=>!v);if(e.key==='Escape'&&mapFocus)setMapFocus(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 const exportSave=()=>{const raw=JSON.stringify(game.session,null,2);setExportJSON(raw);downloadSession(raw,`lordaeron-${game.state.turn}.json`);};
 const importFile=async(f?:File)=>{if(!f)return;try{const next=importSession(p,await f.text());current.current=next;setGame(next);setBots([]);setAuto(false);setHeroId(next.state.heroes[0].id);setSelected(next.state.heroes[0].location);setPanel(null);setToast("Game verified by replaying every move.");}catch(e){setToast((e as Error).message);}if(file.current)file.current.value='';};
 const title=panel==='new'?"New campaign":panel==='settings'?"Your game":panel==='rest'?"Rest":panel==='train'?"Train":panel==='town'?"Town market":panel==='challenge'?"Choose a challenge":panel==='manage'?"Character management":panel==='trade'?"Trade with an ally":card(p,detailCard).name;
 const decision=(state.phase==='reward'||!!state.auction||!!state.eventFlow?.steps.length||state.heroes.some(h=>h.talentChoices.length)||state.respawns.length>0)&&state.phase!=='combat';
 return <div className={`campaign-app ${page==='board'?'desktop-tabletop':''} ${mapFocus?'map-focus':''}`}>
 <header className="topbar"><button className="wordmark" onClick={()=>setPage('board')}><span className="brand-crest"><Icon name="swords" size={29}/></span><span><strong>WORLD <small>of</small> WARCRAFT</strong><em>THE BOARD GAME <i/> 2005 + FAQ</em></span></button><nav className="topnav">{[['board',"Campaign"],['cards',"Card library"],['heroes',"Heroes"],['journal',"Chronicle"],['rules',"Rules"]].map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><div className="header-right"><span className="session-badge"><i/>LOCAL GAME</span><button className="icon-button" aria-label="New game" title="Set up a new campaign" onClick={()=>open('new')}><Icon name="plus"/></button><button className="icon-button" aria-label="Settings" onClick={()=>open('settings')}><Icon name="settings"/></button></div></header>
 <main className="campaign-main"><div className="campaign-title"><div><div className="eyebrow"><span className="chapter-dot"/>LORDAERON <span className="slash">/</span> A WAR OF TWO FACTIONS</div><h1>Fate of the kingdom<span>{phaseLabel[state.phase]}</span></h1></div><div className="campaign-turn"><FactionCrest faction={state.faction}/><span className={state.faction}>{factionLabel(state.faction)}</span><b>{state.turn}<small> / 30{state.lap?` · lap ${state.lap}`:''}</small></b><button className="quiet-button" disabled={!nextPhase} onClick={()=>nextPhase&&send(nextPhase)}>{state.phase==='actions'?"Management":"End turn"}<Icon name="arrow"/></button></div></div>
 {page==='board'&&game.needsSetup&&<section className="campaign-welcome"><span className="sheet-eyebrow">A WAR OF TWO FACTIONS</span><h2>Your adventure begins here.</h2><p>Prepare the table, choose your characters and discover how your first turn works.</p><button className="gold-button" onClick={()=>open('new')}>Set up a campaign <Icon name="arrow"/></button></section>}
 {page==='board'&&!game.needsSetup&&<Tabletop state={state} h={h} legal={legal} controlled={controlled} bots={bots} auto={auto} botReady={botReady} botReason={botReason} selectHero={chooseHero} selected={selected} selectRegion={setSelected} inspect={inspect} open={open} send={send} botStep={botStep} toggleBots={()=>setAuto(v=>!v)} focused={mapFocus} toggleFocus={()=>setMapFocus(v=>!v)} notify={setToast} combatOpen={combatOpen} toggleCombat={()=>setCombatOpen(v=>!v)}/>}
 {page==='cards'&&<BaseCatalog inspect={inspect}/>}
 {page==='heroes'&&<section className="character-codex"><div className="character-roster">{p.characters.map(c=><button key={c.id} aria-pressed={codexHero===c.id} onClick={()=>setCodexHero(c.id)}><HeroPortrait id={c.id} small/><span><strong>{c.name.split(' ')[0]}</strong><small>{c.classId} · {factionLabel(c.faction)}</small></span></button>)}</div><CharacterSheet key={codexHero} hero={state.heroes.find(h=>h.id===codexHero)??startingHero(codexHero)} inspect={inspect} preview/></section>}
 {page==='design'&&<Suspense fallback={<p>Loading…</p>}><DesignGallery/></Suspense>}
 {page==='journal'&&<section className="journal-page"><span className="eyebrow">CHRONICLE OF LORDAERON</span><h2>Your party’s story</h2>{[...state.log].reverse().map(l=><article key={l.id}><span>TURN {l.turn}</span><p>{p.characters.reduce((text,c)=>text.replaceAll(c.id,c.name),l.text)}</p></article>)}</section>}
 {page==='rules'&&<section className="coverage-page"><span className="eyebrow">BASE GAME 2005 + FAQ 1.4</span><h2>Rules for your table</h2><div className="rules-grid"><article><h3>Setup before your first turn</h3><p>Use New game to choose four or six unique classes and balanced factions. The wizard previews starting resources, quests, merchant stock and Overlord setup before play.</p><button className="quiet-button" onClick={()=>open('new')}>Open setup guide</button></article><article><h3>Two actions per character</h3><p>Characters in the active faction take actions in any order: Travel, Rest, Train, Town and Challenge. Actions are followed by a shared equipment management phase.</p></article><article><h3>Combat, step by step</h3><p>Choose the attacker, prepare and roll dice, resolve rerolls and abilities, place hits, assign wounds and resolve combat. Abilities appear when they can be used.</p></article><article><h3>Victory</h3><p>Defeat the chosen Overlord or win the final PvP battle after turn 30. Nefarian can trigger the endgame early by reaching the Bulwark.</p></article><article><h3>AI and local play</h3><p>Bots follow the same rules and legal actions. They cannot see deck order, future rolls or the opposing faction’s hidden Kazzak clues. Online rooms are not yet available.</p></article></div><table><thead><tr><th>Content</th><th>Count</th><th>Verified from scans</th></tr></thead><tbody>{CONTENT_COVERAGE.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.expected}</td><td>{c.note}</td></tr>)}</tbody></table><p className="coverage-note">The map contains {p.regions.length} bordered regions across seven zones. Colored shared borders allow movement; black edges mark impassable terrain. Travel allows up to two steps; a friendly flight costs one. Entering a region with a blue creature ends movement. Quest tokens track remaining objectives, with faction colors. Grey quests are used during setup; replacements come from the green, yellow or red deck.</p><div className="sources-list"><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/wowrules.pdf" target="_blank" rel="noreferrer">Official rulebook <Icon name="arrow"/></a><a href="https://images-cdn.fantasyflightgames.com/ffg_content/WoWBG/WoW_FAQ__v1_4.pdf" target="_blank" rel="noreferrer">FAQ / errata <Icon name="arrow"/></a><button className="quiet-button" onClick={()=>setPage('design')}>Design system</button></div></section>}
 </main>
 {toast&&<div className="toast" role="status"><Icon name="help"/>{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><Icon name="x" size={14}/></button></div>}
 {!game.needsSetup&&<Suspense fallback={combatOpen?<p>Preparing combat…</p>:null}><CampaignCombat state={state} legal={combatPlay||state.battle?.stage==='over'?allLegal:legal} busy={diceRolling} send={send} botStep={botStep} botReady={botReady} auto={auto} toggleBots={()=>setAuto(v=>!v)} open={combatOpen} onClose={()=>setCombatOpen(false)} bots={bots} resolve={combatResolve} toggleResolve={()=>{setCombatResolve(v=>!v);setCombatPlay(false);}} play={combatPlay} togglePlay={()=>setCombatPlay(v=>!v)} automationPending={!!automaticCombat.length}/></Suspense>}
 {state.phase==='combat'&&!combatOpen&&<button className="combat-docked" onClick={()=>setCombatOpen(true)}><Icon name="swords"/><span>Return to combat<small>Round {state.battle?.round} · {phaseLabel[state.battle?.stage??'combat']}</small></span><Icon name="arrow" size={14}/></button>}
 {decision&&<WorldDecision key={`${state.phase}-${state.eventFlow?.event}-${state.eventFlow?.steps[0]?.hero}-${state.heroes.find(h=>h.talentChoices.length)?.id}-${state.reward?.offered.join()}`} state={state} legal={legal} send={send} inspect={inspect} botStep={botStep} botReady={botReady} auto={auto} toggleBots={()=>setAuto(v=>!v)}/>}
 {state.phase==='finished'&&<div className="victory-strip"><Icon name="trophy" size={38}/><h2>{state.winner==='draw'?"The campaign ends in a draw":`${factionLabel(state.winner??'')} wins!`}</h2><p>{state.turn} turns</p><button className="gold-button" onClick={()=>open('new')}>New campaign</button></div>}
 <input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>void importFile(e.target.files?.[0])}/>
 {panel&&<Modal title={title} wide={['new','town','manage','trade','train'].includes(panel)} className={panel==='new'?'setup-modal':panel==='manage'?'equipment-modal':''} onClose={()=>setPanel(null)}>
 {panel==='rest'&&<div className="dialog-content"><p>Friendly town: 3 × level. Wilderness: 2 × level. Rest removes Curse.</p><label className="rest-slider">Health: <b>{restHP}</b><input type="range" min={0} max={Math.max(0,Math.min(cap.health-h.health,h.level*(['both',state.faction].includes(p.regions.find(r=>r.id===h.location)?.town??'')?3:2)))} value={restHP} onChange={e=>setRestHP(Number(e.target.value))}/></label><p>Remaining recovery restores energy, up to your character’s capacity.</p><label className="setting-row">Food<select value={food} onChange={e=>setFood(e.target.value)}><option value="">No food</option>{[...new Set(legal.filter(c=>c.type==='rest'&&c.hero===h.id&&c.food).map(c=>c.type==='rest'?c.food!:''))].map(id=><option key={id} value={id}>{card(p,id).name}</option>)}</select></label><button className="gold-button" onClick={()=>closeAfter({type:'rest',hero:h.id,health:restHP,food:food||undefined})}>Rest · 1 action</button></div>}
 {panel==='train'&&<div className="dialog-content training-dialog"><ClassDeck key={h.id} hero={h} inspect={id=>setTraining(v=>{const c=card(p,id);return c.kind!=='power'||h.learned.includes(id)||c.level>h.level?v:v.includes(id)?v.filter(x=>x!==id):v.reduce((n,x)=>n+card(p,x).price,0)+c.price<=h.gold?[...v,id]:v;})} selected={training} toggle={id=>setTraining(v=>v.includes(id)?v.filter(c=>c!==id):[...v,id])}/><div className="training-receipt"><span><strong>{training.length} powers selected</strong><small>Purchase → Spellbook → Equip during management</small></span><button className="gold-button" disabled={!can('train')||!training.length||training.reduce((n,id)=>n+card(p,id).price,0)>h.gold} onClick={()=>closeAfter({type:'train',hero:h.id,cards:training})}>Learn · {training.reduce((n,id)=>n+card(p,id).price,0)} / {h.gold} gold · 1 action</button></div></div>}
 {panel==='town'&&<TownEditor hero={h} merchant={state.merchant} busy={false} send={closeAfter}/>}
 {panel==='manage'&&<EquipmentEditor key={h.id} hero={h} busy={!can('manage')} send={closeAfter}/>}
 {panel==='trade'&&<TradeEditor hero={h} heroes={state.heroes} busy={false} send={closeAfter}/>}
 {panel==='challenge'&&<div className="dialog-content"><p>Each invited ally spends one action. Blue creatures take priority.</p><div className="challenge-list">{legal.filter((c):c is Extract<Command,{type:'challenge'}>=>c.type==='challenge'&&c.hero===h.id).map((c,i)=>{const e=state.enemies.find(e=>e.id===c.target),creature=p.creatures.find(a=>a.id===e?.creature);const profile=challengeProfile(state,c);const name=creature?.name??p.events.find(e=>e.id===c.target)?.name??p.overlords.find(o=>o.id===c.target)?.name??(c.target==='pvp'?"Enemy party":"Kazzak clue");return <button key={i} className="merchant-row" onClick={()=>closeAfter(c)}>{creature?<CreatureGlyph type={creature.rule}/>:<Icon name="swords" size={30}/>}<span><strong>{profile&&profile.count>1?`${profile.count} × `:""}{name}</strong>{profile&&<span className="challenge-stats"><ThreatLevel value={profile.threat} compact/><span><Icon name="swords" size={13}/>{profile.attack} attack</span><span><Icon name="heart" size={13}/>{profile.health} health</span></span>}<small>{c.region?`${regionName(c.region)} · Intercept · `:''}{c.allies.length?c.allies.map(id=>character(p,id).name.split(' ')[0]).join(' + '):"Solo challenge"}</small></span><Icon name="arrow"/></button>;})}</div></div>}
 {panel==='card'&&<div className="card-detail"><GameCard card={card(p,detailCard)}/><div><h3>{card(p,detailCard).name}</h3><p>Level {card(p,detailCard).level} · {card(p,detailCard).trait||card(p,detailCard).type} · {card(p,detailCard).energy} energy</p><CardRules value={card(p,detailCard)}/><a className="source-link" href={card(p,detailCard).source.url} target="_blank" rel="noreferrer">Original card ↗</a></div></div>}
 {panel==='settings'&&<div className="dialog-content"><div className="settings-buttons"><button className="quiet-button" onClick={exportSave}><Icon name="download"/>Export game</button><button className="quiet-button" onClick={()=>file.current?.click()}><Icon name="upload"/>Import game</button></div>{previousSave&&<button className="quiet-button" onClick={()=>downloadSession(previousSave,'lordaeron-previous-campaign.json')}>Download previous campaign</button>}{legacySave&&<p className="legacy-save-note">Your previous game uses an earlier rules version. It is preserved in a separate save. <button className="quiet-button" onClick={()=>downloadSession(legacySave,'lordaeron-previous-rules-backup.json')}><Icon name="download"/>Download previous game</button></p>}{exportJSON&&<textarea className="save-text" value={exportJSON} readOnly aria-label="Game backup" onFocus={e=>e.target.select()}/>}<label className="setting-row">Bot play style<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="balanced">Balanced</option><option value="cautious">Cautious</option><option value="aggressive">Aggressive</option></select></label><div className="bot-seats">{state.heroes.map(hero=><label key={hero.id}><HeroPortrait id={hero.id} small/><span>{character(p,hero.id).name}</span><input type="checkbox" checked={bots.includes(hero.id)} onChange={e=>setBots(v=>e.target.checked?[...v,hero.id]:v.filter(id=>id!==hero.id))}/>AI</label>)}</div><button className="gold-button full-width" onClick={()=>open('new')}>New campaign</button><p className="muted">Online rooms are not yet available. Your local game saves automatically in this browser.</p></div>}
 {panel==='new'&&<CampaignSetup onStart={reset} onCancel={()=>setPanel(null)} existing={!game.needsSetup}/>}
 </Modal>}
 </div>;
}
