import { useEffect, useRef, useState } from 'react';
import { ABILITIES, heroDefinition } from './data/content';
import { combatStats, getHero, maxEnergy, maxHealth } from './engine/game';
import type { Command, GameState } from './engine/types';
import { Icon, Portrait, ResourceBar } from './components';

export default function Combat({state,dispatch}:{state:GameState;dispatch:(command:Command)=>boolean}){
 const b=state.battle!;const enemy=state.enemies.find(e=>e.id===b.enemyId)!;const [powers,setPowers]=useState<Record<string,string[]>>({});const [selectedDice,setSelectedDice]=useState<number[]>([]);
 const dialog=useRef<HTMLDialogElement>(null);const party=useRef<HTMLDivElement>(null);
 useEffect(()=>{dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[]);
 useEffect(()=>{if(party.current)party.current.scrollTop=0;},[b.stage]);
 const alive=b.participants.map(id=>getHero(state,id)).filter(h=>h.health>0);
 const hits=b.dice.filter(d=>d.value>=enemy.threat);
 const toggle=(id:string,pid:string)=>setPowers(p=>({...p,[id]:(p[id]??[]).includes(pid)?p[id].filter(x=>x!==pid):[...(p[id]??[]),pid]}));
 return <dialog ref={dialog} className={`combat-overlay ${b.outcome??''}`} aria-label="Borba" onCancel={e=>e.preventDefault()}><div className="battle-shell"><div className="battle-top"><span className="eyebrow">{enemy.kind==='boss'?'OVERLORD · ZAVRŠNI SUKOB':'SUKOB U LORDAERONU'}</span><span>RUNDA <b>{b.round.toString().padStart(2,'0')}</b></span></div><div className="enemy-header"><div className="enemy-emblem"><Icon name={enemy.icon} size={38}/></div><div><h2>{enemy.name}</h2><p>{b.remaining} preostalih protivnika · {enemy.kind==='independent'?'Nezavisna stvorenja':enemy.kind==='boss'?'Gospodar Naxxramasa':'Protivnici zadatka'}</p></div><div className="enemy-stats"><span><Icon name="target"/>{enemy.threat}+<small>PRIJETNJA</small></span><span><Icon name="sword"/>{enemy.attack}<small>NAPAD</small></span><span><Icon name="heart"/>{enemy.health}<small>ZDRAVLJE</small></span></div></div>
 <div className="combat-steps">{['Priprema','Kockice','Razrješenje'].map((text,i)=><span key={text} className={['prepare','rolled','resolved'].indexOf(b.stage)===i?'active':''}><i>{i+1}</i>{text}</span>)}</div>
 <div className="battle-body"><div className="battle-party" ref={party}>{b.participants.map(id=>{const h=getHero(state,id);const d=heroDefinition(id);const selected=powers[id]??[];const cost=selected.reduce((n,pid)=>n+(ABILITIES.find(a=>a.id===pid)?.cost??0),0);return <div className={`combat-hero ${h.health<=0?'fallen':''}`} key={id}><div className="combat-hero-title"><Portrait id={id}/><div><h3>{d.name}</h3><span>Nivo {h.level} · {h.health<=0?'Poražen':'Spreman za borbu'}</span></div></div><ResourceBar type="health" value={h.health} max={maxHealth(h)}/><ResourceBar type="energy" value={h.energy} max={maxEnergy(h)}/>{b.stage==='prepare'&&!b.outcome&&h.health>0&&<div className="power-selection">{ABILITIES.filter(a=>h.learned.includes(a.id)).map(a=><button key={a.id} className={selected.includes(a.id)?'selected':''} onClick={()=>toggle(id,a.id)} disabled={!selected.includes(a.id)&&cost+a.cost>h.energy}><Icon name={a.icon}/><span>{a.name}<small>{a.description}</small></span><b>{a.cost}<Icon name="bolt" size={10}/></b><i>{selected.includes(a.id)?<Icon name="check" size={12}/>:null}</i></button>)}<div className="pool-preview">{Object.entries(combatStats(h,selected).pool).map(([color,num])=><span className={color} key={color}>{num} ◆</span>)}<small>· {cost} energije</small></div></div>}</div>;})}</div><div className="battle-arena">
 {b.stage==='prepare'&&!b.outcome&&<div className="prepare-scene"><div className="battle-rune"><Icon name="swords" size={56}/></div><h3>Pripremi svoj napad</h3><p>Aktiviraj naučene sposobnosti. Plave kockice udaraju prve; crvene brane i zatim nanose štetu.</p><span className="carry-damage">{b.damage>0?`${b.damage} štete preneseno iz prethodne runde`:'Svaka kockica ima 8 strana.'}</span></div>}
 {b.dice.length>0&&<><div className="dice-table" aria-label="Rezultati kockica">{b.dice.map(d=><button key={`${b.round}-${d.id}-${d.value}`} title={`${heroDefinition(d.heroId).name} · ${d.color} ${d.value}${d.rerolled?' · ponovno bačena':''}`} className={`die ${d.color} ${d.value>=enemy.threat?'hit':'miss'} ${selectedDice.includes(d.id)?'selected':''}`} disabled={b.stage!=='rolled'||d.rerolled||!b.rerolls[d.heroId]} aria-label={`Kockica ${d.id+1}: ${d.value}${d.value>=enemy.threat?' pogodak':''}`} onClick={()=>setSelectedDice(ids=>ids.includes(d.id)?ids.filter(id=>id!==d.id):[...ids,d.id])}><span>{d.value}</span>{d.rerolled&&<Icon name="reset" size={10}/>}<small>{heroDefinition(d.heroId).name.split(' ')[0]}</small></button>)}</div><div className="hit-summary"><span className="blue">{hits.filter(d=>d.color==='blue').length}<small>DALJINSKI</small></span><span className="red">{hits.filter(d=>d.color==='red').length}<small>BLISKI</small></span><span className="green">{hits.filter(d=>d.color==='green').length}<small>OKLOP</small></span></div>{b.stage==='rolled'&&<p className="reroll-hint">{Object.values(b.rerolls).some(n=>n>0)?'Odaberi kockice za ponovno bacanje.':'Pogodak je svaki rezultat jednak ili veći od prijetnje.'}</p>}</>}
 {(b.stage==='resolved'||b.outcome)&&<div className="battle-report" aria-live="polite">{b.outcome&&<h3><Icon name={b.outcome==='victory'?'trophy':'skull'} size={25}/>{b.outcome==='victory'?'Pobjeda!':b.outcome==='fled'?'Povlačenje':'Poraz družine'}</h3>}{b.report.map((line,i)=><p key={i}>{line}</p>)}</div>}
 </div></div><div className="battle-footer"><span><Icon name="shield" size={15}/> Skriptirani efekti · d8 sistem</span><div>{b.outcome?<button autoFocus className="gold-button" onClick={()=>dispatch({type:'closeBattle'})}>Povratak na mapu <Icon name="arrow"/></button>:b.stage==='prepare'?<><button className="quiet-button" onClick={()=>dispatch({type:'flee'})}>Povuci družinu</button><button className="gold-button" onClick={()=>{if(dispatch({type:'roll',powers:Object.fromEntries(alive.map(h=>[h.id,powers[h.id]??[]]))}))setSelectedDice([]);}}>Baci kockice <Icon name="spark"/></button></>:b.stage==='rolled'?<>{selectedDice.length>0&&<button className="quiet-button" onClick={()=>{if(dispatch({type:'reroll',dieIds:selectedDice}))setSelectedDice([]);}}>Ponovi ({selectedDice.length}) <Icon name="reset"/></button>}<button className="gold-button" onClick={()=>{setSelectedDice([]);dispatch({type:'resolve'});}}>Razriješi rundu <Icon name="arrow"/></button></>:<button className="gold-button" onClick={()=>{setPowers({});dispatch({type:'nextRound'});}}>Sljedeća runda <Icon name="arrow"/></button>}</div></div></div></dialog>;
}
