import { useEffect, useRef, type CSSProperties, type ReactNode } from 'react';
import { ArrowRight, Axe, BookOpen, Bug, Check, ChevronDown, ChevronRight, CircleHelp, Coins, Compass, Crown, Download, Eye, Fish, Flag, Flame, FlaskConical, Footprints, Heart, Home, Layers, Leaf, Map, MapPin, Maximize2, Minus, Moon, Mountain, Music2, Plus, RotateCcw, ScrollText, Search, Settings2, Shield, Skull, Snowflake, Sparkles, Sun, Sword, Swords, Target, Tent, Trophy, Upload, Users, Volume2, VolumeX, Wind, X, Zap, Lock, type LucideIcon } from 'lucide-react';
import { heroDefinition } from './data/content';
export const ICONS: Record<string,LucideIcon>={arrow:ArrowRight,axe:Axe,book:BookOpen,bug:Bug,check:Check,down:ChevronDown,right:ChevronRight,help:CircleHelp,coins:Coins,compass:Compass,crown:Crown,download:Download,eye:Eye,fish:Fish,flag:Flag,flame:Flame,flask:FlaskConical,walk:Footprints,heart:Heart,home:Home,layers:Layers,leaf:Leaf,map:Map,pin:MapPin,expand:Maximize2,minus:Minus,moon:Moon,mountain:Mountain,music:Music2,plus:Plus,reset:RotateCcw,scroll:ScrollText,search:Search,settings:Settings2,shield:Shield,skull:Skull,snow:Snowflake,spark:Sparkles,sun:Sun,sword:Sword,swords:Swords,target:Target,tent:Tent,trophy:Trophy,upload:Upload,users:Users,sound:Volume2,mute:VolumeX,wind:Wind,x:X,bolt:Zap,lock:Lock};
export function Icon({name,size=18,...props}:{name:string;size?:number;className?:string}) {const Component=ICONS[name]??Sparkles;return <Component size={size} strokeWidth={1.6} aria-hidden="true" {...props}/>;}
export function Portrait({id,className='',style={}}:{id:string;className?:string;style?:CSSProperties}){const d=heroDefinition(id);return <span role="img" aria-label={d.name} className={`portrait ${className}`} style={{backgroundPosition:`${d.portrait%3*50}% ${Math.floor(d.portrait/3)*50}%`,...style}}/>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal();const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev;};},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><div><span className="eyebrow">LORDAERON · CHRONICLES</span><h2>{title}</h2></div><button className="icon-button" aria-label="Close" onClick={onClose}><Icon name="x"/></button></div>{children}</dialog>;
}
export function ResourceBar({type,value,max}:{type:'health'|'energy';value:number;max:number}){return <div className={`resource ${type}`}><div className="resource-heading"><span><Icon name={type==='health'?'heart':'bolt'} size={13}/>{type==='health'?"Health":"Energy"}</span><b>{value}<small> / {max}</small></b></div><div className="resource-track"><div style={{width:`${Math.max(0,Math.min(100,value/max*100))}%`}}/></div></div>;}
