import { useEffect, useState } from 'react';
import { Icon, Modal } from './components';

interface ReferenceCard {id:string;name:string;category:string;back:boolean;image:string;source:string;status:string;}
const CATEGORIES: Record<string,string>={all:'Sve karte',star:'Zeleni predmeti',square:'Plavi predmeti',circle:'Ljubičasti predmeti',chalice:'Artefakti',triangle:'Početna oprema',creature:'Čudovišta'};
export default function Library(){
 const [entries,setEntries]=useState<ReferenceCard[]>([]);const [error,setError]=useState('');const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [page,setPage]=useState(0);const [active,setActive]=useState<ReferenceCard|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/assets/reference/manifest.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Arhiva nije dostupna.');return r.json();}).then(data=>setEntries(data.entries.filter((e:ReferenceCard)=>!e.back))).catch(e=>{if(e.name!=='AbortError')setError('Arhiva nije učitana. Osvježi stranicu ili pokreni import-community.py.');});return()=>controller.abort();},[]);
 const filtered=entries.filter(e=>(category==='all'||e.category===category) && e.name.toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/24));
 return <section className="library content-page"><div className="page-title"><div><span className="eyebrow">ARHIV AZEROTHA</span><h1>Zbirka karata</h1><p>Originalni skenovi. Predmeti, artefakti i stvorenja iz svijeta koji pamtiš.</p></div><span className="count-badge"><Icon name="layers"/>{entries.filter(e=>e.category!=='creature').length} KARTE</span></div><div className="archive-notice"><Icon name="book"/><span>Referentna zbirka iz <a href="https://github.com/eidonia/WowBGAssist" target="_blank" rel="noreferrer">WowBGAssist</a>. Skenovi su dostupni za pregled; njihove sposobnosti još nisu povezane s engineom.</span></div><div className="library-toolbar"><div className="filter-tabs">{Object.entries(CATEGORIES).map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>{setCategory(id);setPage(0);}}>{label}</button>)}</div><label className="search-field"><Icon name="search"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Pronađi kartu…" aria-label="Pretraži karte"/></label></div>{error?<p className="inline-error">{error}</p>:!entries.length?<p className="empty-state">Otvaranje arhive…</p>:<><div className="result-count">{filtered.length} rezultata <span>· klikni kartu za detalje</span></div><div className="reference-grid">{filtered.slice(page*24,(page+1)*24).map(card=><button key={card.id} className={`reference-card ${card.category}`} onClick={()=>setActive(card)}><img src={card.image} alt={card.name} loading="lazy"/><div><span>{CATEGORIES[card.category]}</span><h3>{card.name}</h3><Icon name="expand" size={14}/></div></button>)}</div>{!filtered.length&&<p className="empty-state">Nema karata za ovu pretragu.</p>}<div className="pagination"><button className="quiet-button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Prethodna</button><span>{page+1} / {pages}</span><button className="quiet-button" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>Sljedeća</button></div></>}{active&&<Modal title={active.name} onClose={()=>setActive(null)}><div className="scan-view"><img src={active.image} alt={active.name}/><div className="scan-meta"><span className="eyebrow">ORIGINALNI SKEN · REFERENCA</span><p>{CATEGORIES[active.category]}</p><p>Ova karta je arhivirana. Tekst sa skena nije automatski pretvoren u pravila igre.</p><a href={active.source} target="_blank" rel="noreferrer" className="quiet-button">Otvori izvor <Icon name="arrow" size={14}/></a></div></div></Modal>}</section>;
}
