import React from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/cinzel/400.css';
import '@fontsource/cinzel/600.css';
import '@fontsource/cinzel/700.css';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import App from './Campaign';
import './styles.css';
import './campaign/styles.css';
import './campaign/design-system.css';
import './campaign/desktop.css';
import './campaign/warcraft.css';
import './campaign/tabletop.css';
import './campaign/map.css';
import './campaign/command-table.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
