import React from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/cinzel/400.css';
import '@fontsource/cinzel/600.css';
import '@fontsource/cinzel/700.css';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import App from './Campaign';
import './styles.css';
import './campaign/styles.css';
import './campaign/design-system.css';
import './campaign/desktop.css';
import './campaign/warcraft.css';
import './campaign/tabletop.css';
import './campaign/map.css';
import './campaign/command-table.css';
import './campaign/character-sheet.css';
import './campaign/combat.css';
import './campaign/full-cards.css';
import './campaign/upgrade.css';
import './campaign/ui-polish.css';
import './campaign/rules-text.css';
import './campaign/premium-ui.css';
import './campaign/ability-cards.css';
import './campaign/quest-visibility.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
